### ISSUE TITLE
Fatal error:java.lang.NoClassDefFoundError: com/mycompany/sample/Main (wrong name: com/mycompany/sample/main)

### ISSUE THREAD

**Issue by Hilal-Anwar** [gluonhq/substrate#1048]
### Expected Behavior
I was trying to create native image and got an error like this
Warning: Ignoring server-mode native-image argument --no-server.
[com.mycompany.sample.main:7752]    classlist:   9,947.35 ms,  0.96 GB
[com.mycompany.sample.main:7752]        (cap):  12,212.64 ms,  0.95 GB
[com.mycompany.sample.main:7752]        setup:  32,516.01 ms,  0.95 GB
Fatal error:java.lang.NoClassDefFoundError: com/mycompany/sample/Main (wrong name: com/mycompany/sample/main)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:512)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:420)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:414)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:691)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:413)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at com.oracle.svm.util.ModuleSupport.getResourceBundle(ModuleSupport.java:56)
	at com.oracle.svm.core.jdk.localization.LocalizationFeature.prepareBundle(LocalizationFeature.java:461)
	at com.oracle.svm.core.jdk.localization.LocalizationFeature.processRequestedBundle(LocalizationFeature.java:433)
	at com.oracle.svm.core.jdk.localization.LocalizationFeature.addResourceBundles(LocalizationFeature.java:419)
	at com.oracle.svm.core.jdk11.localization.LocalizationFeatureJDK11OrLater.addResourceBundles(LocalizationFeatureJDK11OrLater.java:59)
	at com.oracle.svm.core.jdk.localization.LocalizationFeature.beforeAnalysis(LocalizationFeature.java:258)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$11(NativeImageGenerator.java:691)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:71)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:691)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:532)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:491)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:380)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:543)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:573)
[com.mycompany.sample.main:7752]      [total]:  43,435.45 ms,  0.95 GB
# Printing build artifacts to: C:\Users\ABC.ABC-PC\IdeaProjects\cat\target\gluonfx\x86_64-windows\gvm\cat\com.mycompany.sample.main.build_artifacts.txt
Error: Image build request failed with exit status 1

### Current Behavior
I created the project from https://start.gluon.io.
I cannot figure out what is wrong
Please do help me

### Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -
[process-compile-1638033202160.log](https://github.com/gluonhq/substrate/files/7612156/process-compile-1638033202160.log)
->

**Comment by jperedadnr** [comment]
The default project generated from start.gluon.io works perfectly fine for me as is, without any modification, at least if you are using the Gluon's build of GraalVM. Are you following  https://docs.gluonhq.com/#platforms_windows ?

**Comment by Hilal-Anwar** [comment]
Thanks for your response jperedadnr
I tried using Gluon's build of GraalVM as told but got same error.
I following the steps as in https://github.com/gluonhq/gluon-samples/tree/master/HelloFXML
I am on windows 10.
JavaFx modules thar I am using.

### JavaFX 17.0.1 Modules

 - javafx-base
 - javafx-graphics
 - javafx-controls
 - javafx-fxml
[process-compile-1639811002375.log](https://github.com/gluonhq/substrate/files/7739088/process-compile-1639811002375.log)

**Comment by jperedadnr** [comment]
I still can't reproduce your issue. Can you zip your project (pom+src)?

**Comment by Hilal-Anwar** [comment]
Ok 
My project zip file
[gluon-application (1).zip](https://github.com/gluonhq/substrate/files/7740496/gluon-application.1.zip)

**Comment by jperedadnr** [comment]
Thanks, I can reproduce it now on Windows.
For a quick workaround you can rename the `Main` class to `MainApp` (and update `main.class` in your pom).

**Comment by Hilal-Anwar** [comment]
Thanks a lot, it is working now
You where right,I rename the Main class to MainApp and it is working fine
![Screenshot 2021-12-19 204813](https://user-images.githubusercontent.com/50636048/146680890-ad864812-26e3-48e9-bce9-be3dccb02326.jpg)
![Screenshot 2021-12-19 204943](https://user-images.githubusercontent.com/50636048/146680892-b27a5da1-1839-4912-a519-484bf9246dbf.jpg)

**Comment by Hilal-Anwar** [comment]
Is this bug fixed or still their.
I am just asking out of curiosity
