### ISSUE TITLE
[Android] Could not load @font-face font

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/substrate#1114]
Using GraalVM 22.0.0.3/JDK 17, HelloFX with this CSS changes:
```
@font-face {
    font-family: Roboto;
    src: url('Roboto-Regular.ttf');
}

.label {
    -fx-text-fill: blue;
    -fx-font-family: "Roboto";
}
```
fails on Android. Same code works fine with GraalVM 22.0.0.3/JDK 11 or in other platforms.

With 11:
```
[SUB] D/GraalCompiled(32048):  WARNING: java.lang.UnsatisfiedLinkError
[SUB] E/GraalGluon(32048): In dummy JNI_OnLoad_javafx_font
[SUB] D/GraalCompiled(32048): System.loadLibrary(javafx_font) succeeded
[SUB] D/GraalCompiled(32048): WARNING: java.lang.UnsatisfiedLinkError
[SUB] D/GraalCompiled(32048): System.loadLibrary(javafx_font_freetype) succeeded
```
With 17:
```
[SUB] D/GraalCompiled(32422): WARNING: java.lang.UnsatisfiedLinkError
[SUB] E/GraalGluon(32422): In dummy JNI_OnLoad_javafx_font
[SUB] D/GraalCompiled(32422): System.loadLibrary(javafx_font) succeeded
[SUB] D/GraalCompiled(32422): WARNING: java.lang.UnsatisfiedLinkError
[SUB] D/GraalCompiled(32422): System.loadLibrary(javafx_font_freetype) succeeded
[SUB] D/GraalCompiled(32422): Feb 08, 2022 5:06:13 PM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
[SUB] D/GraalCompiled(32422): INFO: Could not load @font-face font [resource:hellofx/Roboto-Regular.ttf]
[SUB] D/GraalCompiled(32422): File not found: /system/etc/system_fonts.xml
```

**Comment by jperedadnr** [comment]
With GraalVM 17, the reason for the failure is related to #1115 :

```
java.security.PrivilegedActionException: java.io.IOException: Unable to create temporary file
D/GraalCompiled(11617):     at java.security.AccessController.wrapException(AccessController.java:828)
D/GraalCompiled(11617):     at java.security.AccessController.doPrivileged(AccessController.java:573)
D/GraalCompiled(11617):     at com.sun.javafx.font.FontFileWriter.openFile(FontFileWriter.java:87)
D/GraalCompiled(11617):     at com.sun.javafx.font.PrismFontFactory.loadEmbeddedFont0(PrismFontFactory.java:1458)
D/GraalCompiled(11617):     at com.sun.javafx.font.PrismFontFactory.loadEmbeddedFont(PrismFontFactory.java:1422)
...
D/GraalCompiled(11617): Caused by: java.io.IOException: Unable to create temporary file
D/GraalCompiled(11617):     at com.sun.javafx.font.FontFileWriter.lambda$openFile$0(FontFileWriter.java:93)
D/GraalCompiled(11617):     at java.security.AccessController.executePrivileged(AccessController.java:145)
D/GraalCompiled(11617):     at java.security.AccessController.doPrivileged(AccessController.java:569)
D/GraalCompiled(11617):     ... 42 more
```

**Comment by jperedadnr** [comment]
How to reproduce with HelloWorld:
```
public static void main(String[] args) {
        System.out.println("Hello World!!");
        try {
            Files.createTempFile("+JXF", ".tmp").toFile();
        } catch (IOException e) {
            e.printStackTrace();
        }
        System.exit(0);
    }
```
Gives:
```
D/GraalCompiled(12012): Hello World!!
D/GraalCompiled(12012): java.nio.file.NoSuchFileException: /tmp/+JXF12661050881669947642.tmp
D/GraalCompiled(12012):     at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
D/GraalCompiled(12012):     at java.nio.file.Files.newByteChannel(Files.java:380)
D/GraalCompiled(12012):     at java.nio.file.Files.createFile(Files.java:658)
D/GraalCompiled(12012):     at java.nio.file.TempFileHelper.create(TempFileHelper.java:136)
D/GraalCompiled(12012):     at java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:159)
D/GraalCompiled(12012):     at java.nio.file.Files.createTempFile(Files.java:923)
D/GraalCompiled(12012):     at hello.HelloWorld.main(HelloWorld.java:37)
```

**Comment by jperedadnr** [comment]
For reference, this issue https://github.com/oracle/graal/issues/1035 was fixed some time ago with some changes in [JavaNIOSubstitutions.java](https://github.com/gluonhq/substrate/issues/1114#diff-c9b9285482e9db7b67eb4333355e05cc407c587d074adb46b20ff7de12f33b91), but later on the file was removed before GraalVM 20.1 release.

Currently, Target_jdk_internal_util_StaticProperty.java has:

```
@Substitute
    @TargetElement(onlyWith = JDK17OrLater.class)
    private static String javaIoTmpDir() {
        return ImageSingletons.lookup(SystemPropertiesSupport.class).javaIoTmpDir();
    }
```
and this hardcoded [path](https://github.com/oracle/graal/blob/7987f2255f81fc7edcbc4af9562670ba9acd874c/substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/linux/LinuxSystemPropertiesSupport.java#L43):

```
public class LinuxSystemPropertiesSupport extends PosixSystemPropertiesSupport {

    @Override
    protected String javaIoTmpdirValue() {
        /*
         * The initial value of `java.io.tmpdir` is hard coded in libjava when building the JDK. So
         * to be completely correct, we would have to use the value from libjava, but since it is
         * normally initialized to `/tmp` via `P_tmpdir`, this should be fine for now.
         */
        return "/tmp";
    }
```

On Android, it should be `java.io.tmpdir: /data/user/0/com.gluonhq.samples.helloworld`.

Related commit: https://github.com/oracle/graal/commit/ce28fae6837f034e756251dfbca6812412d5d9ca

**Comment by jperedadnr** [comment]
Filed: https://github.com/oracle/graal/issues/4497

**Comment by nlisker** [comment]
Do I need to update the maven plugin version to 1.0.14 to get the fix for this?

**Comment by nlisker** [comment]
I'm using the GitHub Action https://github.com/gluonhq/setup-graalvm, so I think that one is taken care of :)
