### ISSUE TITLE
Watchdog detects no activity and kills the process

### ISSUE THREAD

**Issue by barry-gq** [gluonhq/substrate#1168]
**Environment**：
macos

openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment GraalVM CE 22.2.0 (build 11.0.16+8-jvmci-22.2-b06)
OpenJDK 64-Bit Server VM GraalVM CE 22.2.0 (build 11.0.16+8-jvmci-22.2-b06, mixed mode, sharing)

**Q：I wrote a HellWorld test class for local compilation and testing, but the following error occurred**
 
ps：I used the graalVM 21+ version at first, and this problem also occurred at that time. Later, I found a similar problem in the issue（https://github.com/oracle/graal/issues/2283）, and the description has been solved. Later, I upgraded the graalVM version, but the problem still exists.

cmd：**native-image HelloWorld** 

WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
========================================================================================================================
GraalVM Native Image: Generating 'helloworld' (executable)...
========================================================================================================================

[1/7] Initializing...                                                                                   (46.3s @ 0.10GB)
 Version info: 'GraalVM 22.2.0 Java 11 CE'
 Java version info: '11.0.16+8-jvmci-22.2-b06'
 C compiler: cc (apple, x86_64, 13.1.6)
 Garbage collector: Serial GC
                                 
=== Image generator watchdog detected no activity. This can be a sign of a deadlock during image building. Dumping all stack traces. Current time: Wed Aug 17 14:22:27 CST 2022
"main" Id=1 in RUNNABLE
    at java.base@11.0.16/java.nio.file.Files$2.hasNext(Files.java:3708)
    at java.base@11.0.16/java.util.Iterator.forEachRemaining(Iterator.java:132)
    at java.base@11.0.16/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.base@11.0.16/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ClassLoaderSupportImpl.scanDirectory(ClassLoaderSupportImpl.java:168)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ClassLoaderSupportImpl.collectResources(ClassLoaderSupportImpl.java:109)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ResourcesFeature.duringAnalysis(ResourcesFeature.java:266)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$10(NativeImageGenerator.java:734)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator$$Lambda$827/0x00000007c0e76040.accept(Unknown Source)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:78)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$11(NativeImageGenerator.java:734)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator$$Lambda$521/0x00000007c0d88c40.apply(Unknown Source)
    at app/org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis.runAnalysis(PointsToAnalysis.java:755)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:731)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:564)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:521)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)

"Reference Handler" Id=2 in RUNNABLE
    at java.base@11.0.16/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
    at java.base@11.0.16/java.lang.ref.Reference.processPendingReferences(Reference.java:241)
    at java.base@11.0.16/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:213)

"Finalizer" Id=3 in WAITING on lock=java.lang.ref.ReferenceQueue$Lock@4dd3b6c7
    at java.base@11.0.16/java.lang.Object.wait(Native Method)
    at java.base@11.0.16/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
    at java.base@11.0.16/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
    at java.base@11.0.16/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:170)

"Signal Dispatcher" Id=4 in RUNNABLE

"JVMCI-native CompilerThread0" Id=6 in RUNNABLE

"Common-Cleaner" Id=9 in TIMED_WAITING on lock=java.lang.ref.ReferenceQueue$Lock@4e2fab8e
    at java.base@11.0.16/java.lang.Object.wait(Native Method)
    at java.base@11.0.16/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
    at java.base@11.0.16/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:148)
    at java.base@11.0.16/java.lang.Thread.run(Thread.java:829)
    at java.base@11.0.16/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:161)

"Thread-1" Id=19 in RUNNABLE
    at java.management@11.0.16/sun.management.ThreadImpl.dumpThreads0(Native Method)
    at java.management@11.0.16/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:521)
    at java.management@11.0.16/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:509)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.DeadlockWatchdog.threadDump(DeadlockWatchdog.java:113)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.DeadlockWatchdog.watchdogThread(DeadlockWatchdog.java:80)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.DeadlockWatchdog$$Lambda$179/0x00000007c0287440.run(Unknown Source)
    at java.base@11.0.16/java.lang.Thread.run(Thread.java:829)

"ForkJoinPool-4-worker-3" Id=25 in WAITING on lock=java.util.concurrent.ForkJoinPool@350cf2c7
    at java.base@11.0.16/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.16/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
    at java.base@11.0.16/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
    at java.base@11.0.16/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"ForkJoinPool-2-worker-13" Id=38 in WAITING on lock=java.util.concurrent.ForkJoinPool@1f354e7c
    at java.base@11.0.16/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.16/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
    at java.base@11.0.16/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
    at java.base@11.0.16/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

=== Memory statistics (in MB):
=== Used heap size: 12376
=== Free heap size: 3632
=== Maximum heap size: `12376`
=== Image generator watchdog is aborting image generation. To configure the watchdog, use the options -H:DeadlockWatchdogInterval=10 and -H:+DeadlockWatchdogExitOnTimeout
Error: Image build request failed with exit status 1

how do I fix it

**Comment by barry-gq** [comment]
sorry I wrote in the wrong place
