### ISSUE TITLE
Android APK not executable due to "dlopen failed: cannot locate symbol "JNI_OnLoad_lcms" "

### ISSUE THREAD

**Issue by taranion** [gluonhq/substrate#1177]
Sorry, follow-up error :(

An application built with GluonFX client plugin 1.0.16-SNAPSHOT is not executable on Android (13).

```
10-05 23:29:23.404  6069  6069 E AndroidRuntime: Process: de.rpgframework.shadowrun6.commlink6, PID: 6069
10-05 23:29:23.404  6069  6069 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "JNI_OnLoad_lcms" referenced by "/data/app/~~qPK4wpBbSlUPp3sVw3uzDw==/de.rpgframework.shadowrun6.commlink6-4J-j_DuVyQF5syElmaeveA==/lib/arm64/libsubstrate.so"...
10-05 23:29:23.404  6069  6069 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
10-05 23:29:23.404  6069  6069 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
10-05 23:29:23.404  6069  6069 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1661)
10-05 23:29:23.404  6069  6069 E AndroidRuntime: 	at com.gluonhq.helloandroid.MainActivity.surfaceCreated(MainActivity.java:112)
10-05 23:29:23.404  6069  6069 E AndroidRuntime: 	at android.view.SurfaceView.updateSurface(SurfaceView.java:1000)
10-05 23:29:23.404  6069  6069 E AndroidRuntime: 	at android.view.SurfaceView.lambda$new$0$android-view-SurfaceView(SurfaceView.java:160)
```

### Your Environment
Fedora Linux 36
Substrate 0.0.56-SNAPSHOT  (Android 31)
graalvm-svm-java17-linux-gluon-22.1.0.1-Final

**Comment by jperedadnr** [comment]
It looks like you are trying to use AWT in your project (directly or via dependencies) but that is not supported (it is only partially supported on Linux).
