### ISSUE TITLE
windows 10 Enterprise

### ISSUE THREAD

**Issue by Hugolarson** [gluonhq/substrate#1212]
Hello,

graalvm-ce-java17-22.3.1
JavaFx 19.0.2.1+1

When running native image on Windows 10 Enterprise we get following exception. 
The UI starts showing crashes eventually.
We have tried on several computers with same result. The native image works fine on windows 10 Home and pro. Works also on windows 7 home and pro.

23-03-12 12:35:03| [JavaFX Application Thread|]:advit.log.LoggerHelper uncaughtException JavaFX Application Thread 
java.lang.NoSuchMethodError: com.sun.glass.ui.win.WinAccessible.GetPatternProvider(I)J
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1259)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1244)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions.GetMethodID(JNIFunctions.java:407)
	at com.sun.glass.ui.win.WinAccessible._initIDs(WinAccessible.java)
	at com.sun.glass.ui.win.WinAccessible.<clinit>(WinAccessible.java:72)
	at com.sun.glass.ui.win.WinApplication.createAccessible(WinApplication.java:297)
	at javafx.scene.Scene.getAccessible(Scene.java:6490)
	at javafx.scene.Scene$ScenePeerListener.getSceneAccessible(Scene.java:2900)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.getSceneAccessible(GlassViewEventHandler.java:1390)
	at com.sun.glass.ui.View.getAccessible(View.java:1112)
	at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base@17.0.6/java.lang.Thread.run(Thread.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:178)
23-03-12 12:35:03| [JavaFX Application Thread|]:advit.log.LoggerHelper uncaughtException JavaFX Application Thread 
java.lang.NoClassDefFoundError: Could not initialize class com.sun.glass.ui.win.WinAccessible
	at com.sun.glass.ui.win.WinApplication.createAccessible(WinApplication.java:297)
	at javafx.scene.Scene.getAccessible(Scene.java:6490)
	at javafx.scene.Scene$ScenePeerListener.getSceneAccessible(Scene.java:2900)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.getSceneAccessible(GlassViewEventHandler.java:1390)
	at com.sun.glass.ui.View.getAccessible(View.java:1112)
	at com.sun.glass.ui.win.WinApplication._enterNestedEventLoopImpl(WinApplication.java)
	at com.sun.glass.ui.win.WinApplication._enterNestedEventLoop(WinApplication.java:211)
	at com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:515)
	at com.sun.glass.ui.EventLoop.enter(EventLoop.java:107)
	at com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:648)
	at javafx.stage.Stage.showAndWait(Stage.java:469)
	at javafx.scene.control.HeavyweightDialog.showAndWait(HeavyweightDialog.java:162)
	at javafx.scene.control.Dialog.showAndWait(Dialog.java:345)

**Comment by kristofdho** [comment]
It looks like your windows 11 box has accessibility features enabled through screen readers, narator, or language tools such as grammarly. Your other boxes don't seem to have that.
All you're missing is additional JNI calls, run the agent (or whatever you do to construct config files) on your windows 11 box and you'll catch them.

**Comment by Hugolarson** [comment]
Hi,
I run the agent on the Windows 10 Enterprise box and it started.
I compared content of construct config files and noted very few unrelated changes.
Unfortunately the problem persists.
We have tried on several Windows 10 Enterprise computers.

**Comment by kristofdho** [comment]
Not sure why it doesn't get picked up, either way, these are the calls that you are missing: https://github.com/openjdk/jfx/blob/jfx17/modules/javafx.graphics/src/main/native-glass/win/GlassAccessible.cpp#L1071-L1271

**Comment by Hugolarson** [comment]
Could you please elaborate.
I don't have a clue about how to apply those JNI calls in the construct config files so I can test.
Thanks.
