### ISSUE TITLE
Missing CAP cache value for: NativeCodeInfo:PosixDirectives:ConstantInfo:CLOCK_REALTIME (android)

### ISSUE THREAD

**Issue by Hugolarson** [gluonhq/substrate#1238]
Using substrate 0.0.61 with maven plugin 1.0.22 on Ubuntu 22.04 Wsl2

mvn -Pandroid  gluonfx:build

[Wed Dec 06 16:28:15 CET 2023][INFO] [SUB] Error: Missing CAP cache value for: NativeCodeInfo:PosixDirectives:ConstantInfo:CLOCK_REALTIME
[Wed Dec 06 16:28:15 CET 2023][INFO] [SUB] com.oracle.svm.core.util.UserError$UserException: Missing CAP cache value for: NativeCodeInfo:PosixDirectives:ConstantInfo:CLOCK_REALTIME
[Wed Dec 06 16:28:15 CET 2023][INFO] [SUB]      at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
[Wed Dec 06 16:28:15 CET 2023][INFO] [SUB]      at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.info.InfoTreeVisitor.processChildren(InfoTreeVisitor.java:78)

**Comment by Hugolarson** [comment]
graalvm-community-openjdk-21.0.1+12.1

I thought the latest fix on Substrate fixed this issue.
It's sad that for mobile we are stuck with old Jre and JavaFX

**Comment by laurenzfromme5** [comment]
I am running into the same problem with the latest Gluons GraalVm build ([GraalVM CE Gluon 23+25.1-dev-2409082136]).  Here is a failed hellogluon sample build in Github actions:
https://github.com/laurenzfromme5/gluon-test/actions/runs/23430063137/job/68153908311 

While attempting to build, I run into the same Error Missing CAP cache value for... . I also tried with the 22.1.0.1-Final build and an older version of gluonfx-maven-plugin and that build sucessfully.  Is this a known issue of the newer GraalVm builds? 

Thanks for any help :-)

**Comment by ctoabidmaqbool** [comment]
Hi,

From my experience, this issue is mainly related to the GraalVM version compatibility with Gluon’s toolchain.

The latest GluonFX plugins (both Maven and Gradle), such as:

* gluonfx-maven-plugin (1.0.28)
* gluonfx-gradle-plugin (1.0.28)

are currently most stable when used with the **official Gluon GraalVM stable release**:

* GraalVM 22.1.0.1-Final (Gluon build)

Newer GraalVM builds like:

* GraalVM Gluon 23+25.1-dev

are **experimental/dev builds** and may not fully work with the current GluonFX plugins. Issues like *“Missing CAP cache value…”* are known to appear due to incomplete or evolving native-image support in those versions.

Also worth noting:

* GluonFX plugin versions **1.0.24–1.0.25** had some experimental support for newer GraalVM (23+) and VMOne, but these were not fully stable.
* For production or reliable builds, sticking to the **22.1.0.1-Final Gluon GraalVM** is still the recommended approach.

So for now, the safest setup is:

* GluonFX plugin ≥ 1.0.28
* GraalVM = 22.1.0.1-Final (Gluon)

Until Gluon officially aligns newer GraalVM releases with the toolchain, using dev builds may lead to these kinds of errors.

Hope this helps 👍

**Comment by laurenzfromme5** [comment]
Thanks for the reply. I got it working now with GraalVM 22.1.0.1 and GluonFX plugin 1.0.28. I am trying to build the sample project of gluon for ios. In the docs the sample logs  show under https://docs.gluonhq.com/#platforms_ios_sample that 
`Java version: 23+25, vendor version: GraalVM CE 23-dev+25.1`
was being used. Therefore I guess it should be possible/intended to use newer GraalVM builds. As I am using gluons sample for testing this, maybe there is another source of error. 

Additional note: The sample project still has GluonFX plugin 1.0.27.
