### ISSUE TITLE
Could not find agent library native-image-agent on the library path, with error: Can't find dependent libraries

### ISSUE THREAD

**Issue by ctoabidmaqbool** [gluonhq/substrate#1276]
Using, **gluon-maven-plugin 1.0.24-snapshot** release

```
D:\GraalVM-Projects\gluonhq\hello-gluon-ci>mvnw -Pdesktop gluonfx:runagent
[0.330s][warning][jit,compilation] JVMCI compiler disabled after 11 of 11 upcalls had errors (Last error: "uncaught exception in call_HotSpotJVMCIRuntime_compileMethod [jdk.vm.ci.common.JVMCIError: VM config values missing that should be present in JDK 23 jvmci-23+25-jvmci-b01 windows-amd64 (java.home=D:\Programs\graalvm-java23-windows-amd64-gluon-23+25.1-dev, java.vm.name=OpenJDK 64-Bit Server VM, java.vm.version=23+25-jvmci-b01):
    HeapRegion::LogOfHRGrainBytes at jdk.graal.compiler/jdk.graal.compiler.hotspot.GraalHotSpotVMConfig.<init>(GraalHotSpotVMConfig.java:400)
Set the debug.jdk.graal.jvmciConfigCheck system property to "ignore" to suppress this error or to "warn" to emit a warning and continue execution.
Currently used Java home directory is D:\Programs\graalvm-java23-windows-amd64-gluon-23+25.1-dev.
Currently used VM configuration is: OpenJDK 64-Bit Server VM
]"). Use -Xlog:jit+compilation for more detail.
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------< com.gluonhq.samples:hellogluon >-------------------
[INFO] Building HelloGluon 1.0.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] >>> gluonfx-maven-plugin:1.0.24-SNAPSHOT:runagent (default-cli) > process-classes @ hellogluon >>>
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hellogluon ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ hellogluon ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] <<< gluonfx-maven-plugin:1.0.24-SNAPSHOT:runagent (default-cli) < process-classes @ hellogluon <<<
[INFO]
[INFO]
[INFO] --- gluonfx-maven-plugin:1.0.24-SNAPSHOT:runagent (default-cli) @ hellogluon ---
Configuration: ProjectConfiguration{graalPath='D:\Programs\graalvm-java23-windows-amd64-gluon-23+25.1-dev', javaStaticSdkVersion='24-1', javafxStaticSdkVersion='24-ea+7.1', javaVersion=23, graalVersion=23, useJNI=true, useJavaFX=true, usePrismSW=false, enableCheckHash=true, targetTriplet=x86_64-microsoft-windows, hostTriplet=x86_64-microsoft-windows, backend='null', bundlesList=[], resourcesList=[], reflectionList=[], jniList=[], initBuildTimeList=[], runtimeArgsList=[], releaseSymbolsList=null, appName='HelloGluon', releaseConfiguration='ReleaseConfiguration{packageType=null, description='The HelloGluon app', vendor='Gluon', version='null', macAppStore=false, macSigningUserName=null, macAppCategory=null, bundleName='null', bundleVersion='null', bundleShortVersion='null', providedSigningIdentity='null', providedProvisioningProfile='null', skipSigning=false, simulatorDevice='null', appLabel='null', versionCode='null', versionName='null', providedKeyStorePath='null', providedKeyStorePassword='null', providedKeyAlias='null', providedKeyAliasPassword='null'}', mainClassName='com.gluonhq.hello.HelloGluonApp', classpath='D:\GraalVM-Projects\gluonhq\hello-gluon-ci\target\classes;D:\.my-m2\repository\com\gluonhq\charm-glisten\6.2.3\charm-glisten-6.2.3.jar;C:\Users\MSC-30\.m2\repository\com\gluonhq\attach\display\4.0.21\display-4.0.21-desktop.jar;D:\.my-m2\repository\com\gluonhq\attach\display\4.0.21\display-4.0.21.jar;C:\Users\MSC-30\.m2\repository\com\gluonhq\attach\lifecycle\4.0.21\lifecycle-4.0.21-desktop.jar;D:\.my-m2\repository\com\gluonhq\attach\lifecycle\4.0.21\lifecycle-4.0.21.jar;C:\Users\MSC-30\.m2\repository\com\gluonhq\attach\statusbar\4.0.21\statusbar-4.0.21.jar;D:\.my-m2\repository\com\gluonhq\attach\statusbar\4.0.21\statusbar-4.0.21.jar;C:\Users\MSC-30\.m2\repository\com\gluonhq\attach\storage\4.0.21\storage-4.0.21-desktop.jar;D:\.my-m2\repository\com\gluonhq\attach\storage\4.0.21\storage-4.0.21.jar;D:\.my-m2\repository\com\gluonhq\attach\util\4.0.21\util-4.0.21.jar;D:\.my-m2\repository\org\openjfx\javafx-base\24-ea+5\javafx-base-24-ea+5-win.jar;D:\.my-m2\repository\org\openjfx\javafx-base\24-ea+5\javafx-base-24-ea+5.jar;D:\.my-m2\repository\org\openjfx\javafx-controls\24-ea+5\javafx-controls-24-ea+5-win.jar;D:\.my-m2\repository\org\openjfx\javafx-controls\24-ea+5\javafx-controls-24-ea+5.jar;D:\.my-m2\repository\org\openjfx\javafx-graphics\24-ea+5\javafx-graphics-24-ea+5-win.jar;D:\.my-m2\repository\org\openjfx\javafx-graphics\24-ea+5\javafx-graphics-24-ea+5.jar'}
[WARN] Maven will be executed in interactive mode, but no input stream has been configured for this MavenInvoker instance.
[0.317s][warning][jit,compilation] JVMCI compiler disabled after 11 of 11 upcalls had errors (Last error: "uncaught exception in call_HotSpotJVMCIRuntime_compileMethod [jdk.vm.ci.common.JVMCIError: VM config values missing that should be present in JDK 23 jvmci-23+25-jvmci-b01 windows-amd64 (java.home=D:\Programs\graalvm-java23-windows-amd64-gluon-23+25.1-dev, java.vm.name=OpenJDK 64-Bit Server VM, java.vm.version=23+25-jvmci-b01):
    HeapRegion::LogOfHRGrainBytes at jdk.graal.compiler/jdk.graal.compiler.hotspot.GraalHotSpotVMConfig.<init>(GraalHotSpotVMConfig.java:400)
Set the debug.jdk.graal.jvmciConfigCheck system property to "ignore" to suppress this error or to "warn" to emit a warning and continue execution.
Currently used Java home directory is D:\Programs\graalvm-java23-windows-amd64-gluon-23+25.1-dev.
Currently used VM configuration is: OpenJDK 64-Bit Server VM
]"). Use -Xlog:jit+compilation for more detail.
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------< com.gluonhq.samples:hellogluon >-------------------
[INFO] Building HelloGluon 1.0.0-SNAPSHOT
[INFO]   from agentPom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] >>> javafx-maven-plugin:0.0.8:run (default-cli) > process-classes @ hellogluon >>>
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hellogluon ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ hellogluon ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] <<< javafx-maven-plugin:0.0.8:run (default-cli) < process-classes @ hellogluon <<<
[INFO]
[INFO]
[INFO] --- javafx-maven-plugin:0.0.8:run (default-cli) @ hellogluon ---
Error occurred during initialization of VM
Could not find agent library native-image-agent on the library path, with error: Can't find dependent libraries
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.openjfx.JavaFXBaseMojo.executeCommandLine (JavaFXBaseMojo.java:567)
    at org.openjfx.JavaFXBaseMojo.executeCommandLine (JavaFXBaseMojo.java:434)
    at org.openjfx.JavaFXRunMojo.execute (JavaFXRunMojo.java:105)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:299)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:963)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:296)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:199)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at org.openjfx.JavaFXBaseMojo.executeCommandLine(JavaFXBaseMojo.java:567)
        at org.openjfx.JavaFXBaseMojo.executeCommandLine(JavaFXBaseMojo.java:434)
        at org.openjfx.JavaFXRunMojo.execute(JavaFXRunMojo.java:105)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:370)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[INFO] ------------------------------------------------------------------------
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:299)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:963)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:296)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[INFO] Total time:  2.078 s
[INFO] Finished at: 2024-09-08T09:03:25+05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.openjfx:javafx-maven-plugin:0.0.8:run (default-cli) on project hellogluon: Error: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.679 s
[INFO] Finished at: 2024-09-08T09:03:25+05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:gluonfx-maven-plugin:1.0.24-SNAPSHOT:runagent (default-cli) on project hellogluon: Error, javafx:run failed -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by ctoabidmaqbool** [comment]
Same is happening in Linux too:
I am trying to use latest **GraalVM** e.g. 
```
maqboolstudiopc@MSC-30:/mnt/d/GraalVM-Projects/gluonhq/hello-gluon-ci$ java --version
openjdk 23 2024-09-17
OpenJDK Runtime Environment GraalVM CE 23-dev+25.1 (build 23+25-jvmci-b01)
OpenJDK 64-Bit Server VM GraalVM CE 23-dev+25.1 (build 23+25-jvmci-b01, mixed mode, sharing)
```

```
maqboolstudiopc@MSC-30:/mnt/d/GraalVM-Projects/gluonhq/hello-gluon-ci$ ./mvnw -Pdesktop gluonfx:runagent
[1.741s][warning][jit,compilation] JVMCI compiler disabled after 11 of 11 upcalls had errors (Last error: "uncaught exception in call_HotSpotJVMCIRuntime_compileMethod [jdk.vm.ci.common.JVMCIError: VM config values missing that should be present in JDK 23 jvmci-23+25-jvmci-b01 linux-amd64 (java.home=/mnt/d/Programs/graalvm-java23-linux-amd64-gluon-23+25.1-dev, java.vm.name=OpenJDK 64-Bit Server VM, java.vm.version=23+25-jvmci-b01):
    HeapRegion::LogOfHRGrainBytes at jdk.graal.compiler/jdk.graal.compiler.hotspot.GraalHotSpotVMConfig.<init>(GraalHotSpotVMConfig.java:400)
Set the debug.jdk.graal.jvmciConfigCheck system property to "ignore" to suppress this error or to "warn" to emit a warning and continue execution.
Currently used Java home directory is /mnt/d/Programs/graalvm-java23-linux-amd64-gluon-23+25.1-dev.
Currently used VM configuration is: OpenJDK 64-Bit Server VM
]"). Use -Xlog:jit+compilation for more detail.
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------< com.gluonhq.samples:hellogluon >-------------------
[INFO] Building HelloGluon 1.0.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] >>> gluonfx-maven-plugin:1.0.24-SNAPSHOT:runagent (default-cli) > process-classes @ hellogluon >>>
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hellogluon ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ hellogluon ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] <<< gluonfx-maven-plugin:1.0.24-SNAPSHOT:runagent (default-cli) < process-classes @ hellogluon <<<
[INFO]
[INFO]
[INFO] --- gluonfx-maven-plugin:1.0.24-SNAPSHOT:runagent (default-cli) @ hellogluon ---
Configuration: ProjectConfiguration{graalPath='/mnt/d/Programs/graalvm-java23-linux-amd64-gluon-23+25.1-dev', javaStaticSdkVersion='24-1', javafxStaticSdkVersion='24-ea+7.1', javaVersion=23, graalVersion=23, useJNI=true, useJavaFX=true, usePrismSW=false, enableCheckHash=true, targetTriplet=x86_64-linux-linux, hostTriplet=x86_64-linux-linux, backend='null', bundlesList=[], resourcesList=[], reflectionList=[], jniList=[], initBuildTimeList=[], runtimeArgsList=[], releaseSymbolsList=null, appName='HelloGluon', releaseConfiguration='ReleaseConfiguration{packageType=null, description='The HelloGluon app', vendor='Gluon', version='null', macAppStore=false, macSigningUserName=null, macAppCategory=null, bundleName='null', bundleVersion='null', bundleShortVersion='null', providedSigningIdentity='null', providedProvisioningProfile='null', skipSigning=false, simulatorDevice='null', appLabel='null', versionCode='null', versionName='null', providedKeyStorePath='null', providedKeyStorePassword='null', providedKeyAlias='null', providedKeyAliasPassword='null'}', mainClassName='com.gluonhq.hello.HelloGluonApp', classpath='/mnt/d/GraalVM-Projects/gluonhq/hello-gluon-ci/target/classes:/mnt/d/.my-m2/repository/com/gluonhq/charm-glisten/6.2.3/charm-glisten-6.2.3.jar:/home/maqboolstudiopc/.m2/repository/com/gluonhq/attach/display/4.0.21/display-4.0.21-desktop.jar:/mnt/d/.my-m2/repository/com/gluonhq/attach/display/4.0.21/display-4.0.21.jar:/home/maqboolstudiopc/.m2/repository/com/gluonhq/attach/lifecycle/4.0.21/lifecycle-4.0.21-desktop.jar:/mnt/d/.my-m2/repository/com/gluonhq/attach/lifecycle/4.0.21/lifecycle-4.0.21.jar:/home/maqboolstudiopc/.m2/repository/com/gluonhq/attach/statusbar/4.0.21/statusbar-4.0.21.jar:/mnt/d/.my-m2/repository/com/gluonhq/attach/statusbar/4.0.21/statusbar-4.0.21.jar:/home/maqboolstudiopc/.m2/repository/com/gluonhq/attach/storage/4.0.21/storage-4.0.21-desktop.jar:/mnt/d/.my-m2/repository/com/gluonhq/attach/storage/4.0.21/storage-4.0.21.jar:/mnt/d/.my-m2/repository/com/gluonhq/attach/util/4.0.21/util-4.0.21.jar:/mnt/d/.my-m2/repository/org/openjfx/javafx-base/24-ea+5/javafx-base-24-ea+5-linux.jar:/mnt/d/.my-m2/repository/org/openjfx/javafx-base/24-ea+5/javafx-base-24-ea+5.jar:/mnt/d/.my-m2/repository/org/openjfx/javafx-controls/24-ea+5/javafx-controls-24-ea+5-linux.jar:/mnt/d/.my-m2/repository/org/openjfx/javafx-controls/24-ea+5/javafx-controls-24-ea+5.jar:/mnt/d/.my-m2/repository/org/openjfx/javafx-graphics/24-ea+5/javafx-graphics-24-ea+5-linux.jar:/mnt/d/.my-m2/repository/org/openjfx/javafx-graphics/24-ea+5/javafx-graphics-24-ea+5.jar'}
[WARN] Maven will be executed in interactive mode, but no input stream has been configured for this MavenInvoker instance.
[0.291s][warning][jit,compilation] JVMCI compiler disabled after 11 of 11 upcalls had errors (Last error: "uncaught exception in call_HotSpotJVMCIRuntime_compileMethod [jdk.vm.ci.common.JVMCIError: VM config values missing that should be present in JDK 23 jvmci-23+25-jvmci-b01 linux-amd64 (java.home=/mnt/d/Programs/graalvm-java23-linux-amd64-gluon-23+25.1-dev, java.vm.name=OpenJDK 64-Bit Server VM, java.vm.version=23+25-jvmci-b01):
    HeapRegion::LogOfHRGrainBytes at jdk.graal.compiler/jdk.graal.compiler.hotspot.GraalHotSpotVMConfig.<init>(GraalHotSpotVMConfig.java:400)
Set the debug.jdk.graal.jvmciConfigCheck system property to "ignore" to suppress this error or to "warn" to emit a warning and continue execution.
Currently used Java home directory is /mnt/d/Programs/graalvm-java23-linux-amd64-gluon-23+25.1-dev.
Currently used VM configuration is: OpenJDK 64-Bit Server VM
]"). Use -Xlog:jit+compilation for more detail.
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------< com.gluonhq.samples:hellogluon >-------------------
[INFO] Building HelloGluon 1.0.0-SNAPSHOT
[INFO]   from agentPom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] >>> javafx-maven-plugin:0.0.8:run (default-cli) > process-classes @ hellogluon >>>
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hellogluon ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ hellogluon ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] <<< javafx-maven-plugin:0.0.8:run (default-cli) < process-classes @ hellogluon <<<
[INFO]
[INFO]
[INFO] --- javafx-maven-plugin:0.0.8:run (default-cli) @ hellogluon ---
Error occurred during initialization of VM
Could not find agent library native-image-agent on the library path, with error: libnative-image-agent.so: cannot open shared object file: No such file or directory
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.openjfx.JavaFXBaseMojo.executeCommandLine (JavaFXBaseMojo.java:567)
    at org.openjfx.JavaFXBaseMojo.executeCommandLine (JavaFXBaseMojo.java:434)
    at org.openjfx.JavaFXRunMojo.execute (JavaFXRunMojo.java:105)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:299)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:963)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:296)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:199)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at org.openjfx.JavaFXBaseMojo.executeCommandLine(JavaFXBaseMojo.java:567)
        at org.openjfx.JavaFXBaseMojo.executeCommandLine(JavaFXBaseMojo.java:434)
        at org.openjfx.JavaFXRunMojo.execute(JavaFXRunMojo.java:105)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:370)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:299)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:963)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:296)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.878 s
[INFO] Finished at: 2024-09-08T23:14:46+05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.openjfx:javafx-maven-plugin:0.0.8:run (default-cli) on project hellogluon: Error: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  24.559 s
[INFO] Finished at: 2024-09-08T23:14:46+05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:gluonfx-maven-plugin:1.0.24-SNAPSHOT:runagent (default-cli) on project hellogluon: Error, javafx:run failed -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by logicash-pos** [comment]
I have same issue with gradle plugin 
Could not find agent library native-image-agent on the library path, with error: Can't find dependent libraries

**Comment by Hugolarson** [comment]
Same with gradle plugin

**Comment by ctoabidmaqbool** [comment]
Gluon team great works!

In latest GraalVM relase by Gluon, above errors is fixed https://github.com/gluonhq/graal/releases/tag/gluon-23+25.1-dev-2409082136

**Note:** currently check only `Gluon-Maven-Plugin`

**Comment by Hugolarson** [comment]
I have problem with gradlew nativeRunAgent
> Task :nativeRunAgent FAILED
Error: JavaFX runtime components are missing, and are required to run this application

Only gradlew run works.

**Comment by ctoabidmaqbool** [comment]
> Gluon team great works!
> 
> In latest GraalVM relase by Gluon, above error is fixed https://github.com/gluonhq/graal/releases/tag/gluon-23+25.1-dev-2409082136
> 
> **Note:** currently check only `Gluon-Maven-Plugin`

the above problem is yet fixed for only window (Maven mvn or mvnw), still in Linux OS the problem is still there. I have already post logs above for linux
https://github.com/gluonhq/substrate/issues/1276#issuecomment-2336563758
