### ISSUE TITLE
Can't build image on Windows, 404 as vmone-windows-x64.zip doesn't exist

### ISSUE THREAD

**Issue by credmond** [gluonhq/substrate#1280]
Cannot mvn gluonfx:compile on Windows (master using Gluon's GraalVM 23)

### Expected Behavior
It should build the native image.

### Current Behavior
It's trying to download a file that does not exist. There's no "windows" release here, yet substrate is trying to request it @ https://github.com/gluonhq/vmone/releases/tag/gvm-24-1.

```
[Mon Sept 09 23:49:12 IST 2024][INFO] We will now compile your code for x86_64-microsoft-windows. This may take some time.
[Mon Sept 09 23:49:12 IST 2024][FINE] Processing JavaStatic dependencies at C:\Users\credm\.gluon\substrate\javaStaticSdk\24-1\windows-x86_64\lib
[Mon Sept 09 23:49:12 IST 2024][FINE] Processing JavaFXStatic dependencies at C:\Users\credm\.gluon\substrate\javafxStaticSdk\24-ea+7.1\windows-x86_64\sdk\lib
[Mon Sept 09 23:49:12 IST 2024][INFO] Downloading Java Static Libs...
[Mon Sept 09 23:49:12 IST 2024][FINE] Processing zip file: url = https://github.com/gluonhq/vmone/releases/download/gvm-24-1/vmone-windows-x64.zip, zip = C:\Users\credm\.gluon\substrate\gvm-24-1\vmone-windows-x64.zip, subDir = javaStaticSdk, levels = [24-1, windows-x86_64], md5 = javaStaticSdk-windows-x86_64.md5
[Mon Sept 09 23:49:12 IST 2024][FINE] download from link: https://github.com/gluonhq/vmone/releases/download/gvm-24-1/vmone-windows-x64.zip
[Mon Sept 09 23:49:12 IST 2024][SEVERE] download from link failed with status: 404, and body: null
Check the log files under c:\dev\code\ct-ui-kafkatopical\target\gluonfx\x86_64-windows\gvm\log
And please check https://docs.gluonhq.com/ for more information.
java.lang.RuntimeException: Error downloading zips: java.io.IOException: Error downloading link from https://github.com/gluonhq/vmone/releases/download/gvm-24-1/vmone-windows-x64.zip. Unexpected status code: 404
        at com.gluonhq.substrate.util.FileDeps.setupDependencies(FileDeps.java:334)
        at com.gluonhq.substrate.util.FileDeps.resolvePath(FileDeps.java:174)
        at com.gluonhq.substrate.util.FileDeps.getJavaFXSDKLibsPath(FileDeps.java:106)
        at com.gluonhq.substrate.target.AbstractTargetConfiguration.processClassPath(AbstractTargetConfiguration.java:788)
        at com.gluonhq.substrate.target.AbstractTargetConfiguration.validateCompileRequirements(AbstractTargetConfiguration.java:392)
        at com.gluonhq.substrate.target.AbstractTargetConfiguration.compile(AbstractTargetConfiguration.java:131)
        at com.gluonhq.substrate.SubstrateDispatcher.nativeCompile(SubstrateDispatcher.java:422)
        at com.gluonhq.NativeCompileMojo.execute(NativeCompileMojo.java:54)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:370)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:298)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

### Steps to Reproduce
Do a "mvn clean gluonfx:compile" on Windows

### Your Environment
Windows, graalvm-java23-windows-amd64-gluon-23+25.1-dev

**Comment by ctoabidmaqbool** [comment]
https://github.com/gluonhq/hello-gluon-ci/issues/37
