### ISSUE TITLE
ios failure on socket timeout

### ISSUE THREAD

**Issue by johanvos** [gluonhq/substrate#235]
Following code throws a RuntimeException on ios (instead of a SocketTimeoutException):
```
public class HelloWorld {

    static InetAddress local = null; 

    public static void main(String[] args) throws Exception{
        System.out.println("Hello World!!");
        HelloWorld hw = new HelloWorld();
        hw.fakeServer();
        hw.fakeClient();
    }

    private void fakeServer() throws IOException {
        Thread t = new Thread() {
            @Override
            public void run() { 
                try {
                    ServerSocket ss = new ServerSocket(1234);
                    local = ss.getInetAddress();
                    System.err.println("Got local: "+local);
                    Socket child = ss.accept();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

        };
        t.start();
    }

    private void fakeClient() {
        Thread t = new Thread() {
            @Override
            public void run() { 
                try {
                    Thread.sleep(500);
                    System.err.println("create to local: "+local);
                    Socket s = new Socket(local, 1234);
                    s.setSoTimeout(3000);
                    InputStream is = s.getInputStream();
                    is.read();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

        };
        t.start();
    }

}

```

The error is:
```
java.lang.RuntimeException: Invalid object handle
	at com.oracle.svm.jni.JNIObjectHandles.getObject(JNIObjectHandles.java:128)
	at com.oracle.svm.jni.JNIGeneratedMethodSupport.unboxHandle(JNIGeneratedMethodSupport.java:77)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Ljava_net_SocketTimeoutException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
	at com.oracle.svm.jni.functions.JNIFunctions$NewObjectWithObjectArgFunctionPointer.invoke(JNIFunctions.java)
	at com.oracle.svm.jni.functions.JNIFunctions.ThrowNew(JNIFunctions.java:792)
	at java.net.SocketInputStream.socketRead0(SocketInputStream.java)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.net.SocketInputStream.read(SocketInputStream.java:168)
```

**Comment by jperedadnr** [comment]
See: https://github.com/oracle/graal/issues/2090

**Comment by jperedadnr** [comment]
Fixed
