### ISSUE TITLE
java.util.preferences references unresolved symbol _JVM_ArrayCopy

### ISSUE THREAD

**Issue by xzel23** [gluonhq/substrate#260]
Hi, thank you for the quick fix of #237 - the unresolved symbols for `_Java_java_util_prefs_MacOSXPreferences...` are now gone. However something is still missing (at least on MAC). It looks like the libprefs.a has to be also updated because it has an unresolved reference to `_JVM_ArrayCopy":

```
Undefined symbols for architecture x86_64:
  "_JVM_ArrayCopy", referenced from:
      _getStringsForNode in libprefs.a(MacOSXPreferencesFile.o)
ld: symbol(s) not found for architecture x86_64
```

_Originally posted by @xzel23 in https://github.com/gluonhq/substrate/issues/237#issuecomment-572598781_

**Comment by xzel23** [comment]
Steps to reproduce:
 1. clone the [samples](https://github.com/gluonhq/client-samples/tree/master/Maven).
 2. cd into the HelloWorld directory.
 3. Change client.plugin.version to 0.1.11 in pom.xml.
 4. Change content of `src/main/java/hello/HelloWorld.java`to by inserting a call to Preferences packages like shown in the code block:
 5. run `man:build`

Result: linker error
Expected result: no error

-----

```
package hello;

import java.util.prefs.Preferences;

public class HelloWorld {

    public static void main(String[] args) {
        System.out.println("Hello World!!");
        Preferences.systemRoot();
        System.exit(0);
    }

}
```

-----

```
axel@xiaolong HelloWorld % mvn client:build
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------------< hello:helloworld >--------------------------
[INFO] Building helloWorld 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- client-maven-plugin:0.1.11:build (default-cli) @ helloworld ---
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------------< hello:helloworld >--------------------------
[INFO] Building helloWorld 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- client-maven-plugin:0.1.11:compile (default-cli) @ helloworld ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/axel/Development/samples/client-samples/Maven/HelloWorld/src/main/resources
[INFO] Nothing to compile - all classes are up to date
We will now compile your code for x86_64-apple-darwin. This may take some time.
Build on Server(pid: 34469, port: 59513)
[hello.helloworld:34469]    classlist:     193.74 ms
[hello.helloworld:34469]        (cap):   1,579.07 ms
[hello.helloworld:34469]        setup:   1,828.60 ms
[hello.helloworld:34469]   (typeflow):   9,374.20 ms
[hello.helloworld:34469]    (objects):  10,138.31 ms
[hello.helloworld:34469]   (features):     495.23 ms
[hello.helloworld:34469]     analysis:  20,479.12 ms
[hello.helloworld:34469]     (clinit):     414.42 ms
[hello.helloworld:34469]     universe:     757.20 ms
[hello.helloworld:34469]      (parse):     694.54 ms
[hello.helloworld:34469]     (inline):   1,936.66 ms
[hello.helloworld:34469]    (compile):   7,647.43 ms
[hello.helloworld:34469]      compile:  11,274.73 ms
[hello.helloworld:34469]        image:   2,257.02 ms
[hello.helloworld:34469]        write:     230.68 ms
[hello.helloworld:34469]      [total]:  37,097.85 ms
Compilation succeeded.
[INFO] 
[INFO] --- client-maven-plugin:0.1.11:link (default-cli) @ helloworld ---
started linking
done linking
Linking failed. Details from linking below:
Command was: gcc /Users/axel/Development/samples/client-samples/Maven/HelloWorld/target/client/x86_64-darwin/gvm/helloWorld/AppDelegate.o /Users/axel/Development/samples/client-samples/Maven/HelloWorld/target/client/x86_64-darwin/gvm/helloWorld/launcher.o /Users/axel/Development/samples/client-samples/Maven/HelloWorld/target/client/x86_64-darwin/gvm/tmp/SVM-1578664883527/hello.helloworld.o /Users/axel/bin/graalvm/lib/libjava.a /Users/axel/bin/graalvm/lib/libnio.a /Users/axel/bin/graalvm/lib/libzip.a /Users/axel/bin/graalvm/lib/libnet.a /Users/axel/bin/graalvm/lib/libprefs.a /Users/axel/bin/graalvm/lib/libj2pkcs11.a /Users/axel/bin/graalvm/lib/libsunec.a /Users/axel/bin/graalvm/lib/libextnet.a /Users/axel/bin/graalvm/lib/svm/clibraries/darwin-amd64/libffi.a /Users/axel/bin/graalvm/lib/svm/clibraries/darwin-amd64/libjvm.a /Users/axel/bin/graalvm/lib/svm/clibraries/darwin-amd64/libstrictmath.a /Users/axel/bin/graalvm/lib/svm/clibraries/darwin-amd64/liblibchelper.a -lpthread -lz -ldl -lstdc++ -Wl,-framework,Foundation -Wl,-framework,AppKit -o /Users/axel/Development/samples/client-samples/Maven/HelloWorld/target/client/x86_64-darwin/helloWorld -L/Users/axel/bin/graalvm/lib/svm/clibraries/darwin-amd64 -L/Users/axel/bin/graalvm/lib
Undefined symbols for architecture x86_64:
  "_JVM_ArrayCopy", referenced from:
      _getStringsForNode in libprefs.a(MacOSXPreferencesFile.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
java.lang.RuntimeException: Linking failed
	at com.gluonhq.NativeLinkMojo.execute(NativeLinkMojo.java:55)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  40.811 s
[INFO] Finished at: 2020-01-10T15:02:01+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:client-maven-plugin:0.1.11:link (default-cli) on project helloworld: Error: Linking failed -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  42.379 s
[INFO] Finished at: 2020-01-10T15:02:01+01:00
[INFO] ------------------------------------------------------------------------
```

**Comment by xzel23** [comment]
Works after update to release 19.3.1 of GraalVM
