### ISSUE TITLE
No image reader for JPEG files

### ISSUE THREAD

**Issue by mipastgt** [gluonhq/substrate#375]
The attached program, which tries to read some properties from a JPEG image without actually loading it, fails with the following exception.

```
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:497)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: java.lang.UnsatisfiedLinkError: com.sun.imageio.plugins.jpeg.JPEGImageReader.initJPEGImageReader()J [symbol: Java_com_sun_imageio_plugins_jpeg_JPEGImageReader_initJPEGImageReader or Java_com_sun_imageio_plugins_jpeg_JPEGImageReader_initJPEGImageReader__]
	at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)
	at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.initJPEGImageReader(JPEGImageReader.java)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.<init>(JPEGImageReader.java:232)
	at com.sun.imageio.plugins.jpeg.JPEGImageReaderSpi.createReaderInstance(JPEGImageReaderSpi.java:85)
	at javax.imageio.spi.ImageReaderSpi.createReaderInstance(ImageReaderSpi.java:320)
	at javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:532)
	at javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:516)
	at hellofx.HelloImageSizeFX.extractChartSize(HelloImageSizeFX.java:89)
	at hellofx.HelloImageSizeFX.start(HelloImageSizeFX.java:57)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.security.AccessController.doPrivileged(AccessController.java:99)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Ljava_lang_Runnable_2_0002erun_00028_00029V(JNIJavaCallWrappers.java:0)
```
The problem is not that substrate could not display JPEGs. The problem is only in the ImageIO.getImageReaders method. Just adding com.sun.imageio.plugins.jpeg.JPEGImageReader to the jni list also does not help.

macOS 10.14.6
GraalVM 19.3.1
client-maven-plugin 0.1.15
jfx 15-ea+1

[HelloImageSizeFX.java.zip](https://github.com/gluonhq/substrate/files/4236094/HelloImageSizeFX.java.zip)
[openduke.jpg.zip](https://github.com/gluonhq/substrate/files/4236099/openduke.jpg.zip)

**Comment by jperedadnr** [comment]
We have new versions. Can you try:

GraalVM 20.0.0
client-maven-plugin 0.1.16
jfx 15-ea+1

**Comment by mipastgt** [comment]
I just did try it but this new release is completely unusable for me. Even after a long time of waiting I did not get any result. It is also curious that the process, after some initial work, later did not show any activity anymore. It is just silent but does not finish. I guess this is due to the switch to --no-server because some time ago I played with that option myself and got the same result. So I immediately switched back to the default. I don't know exactly what the technical difference between these two modes is and what your motivation was to do the switch but at least it does not work at all for me and there does not seem to be any possibility for me to negate this change.

macOS 10.14.6
GraalVM 20.0.0
client-maven-plugin 0.1.16
jfx 15-ea+1

**Comment by jperedadnr** [comment]
Can you verify that you don't have any other java process running? 
Sometimes it is also convenient to remove .gluon/substrate so all the new dependencies are downloaded fresh.

**Comment by mipastgt** [comment]
There  were no other java processes running (with the exception of Eclipse).
I also cleaned the .gluon folder and tried again. This time it crashed so badly that it took all my current work with it. First the screen was frosen after a few minutes and before I could do anything else the computer switched itself off.
I now switched back to 0.1.15 and the build finished normally after 7min 23s and the resulting binary even worked too. As I said before, I know this behaviour already (except the hard crash) from my own experiments with the --no-server option.

**Comment by jperedadnr** [comment]
Wow, I wouldn't expect that to happen at all. Can you please file a new issue about this?

With 0.1.15, does the jpeg issue remain? If that is the case, can you add this to the plugin and build/run again?
```
<javafxStaticSdkVersion>15-ea+gvm11</javafxStaticSdkVersion>
```

**Comment by mipastgt** [comment]
I filed a new issue https://github.com/gluonhq/client-maven-plugin/issues/136
and the JPEG problem persists even with the additional line from above.

**Comment by mipastgt** [comment]
I filed a new issue https://github.com/gluonhq/client-maven-plugin/issues/136
and the JPEG problem persists even with the additional line from above.

**Comment by jperedadnr** [comment]
Ok, thanks for the issue, and now back to your original jpeg issue. I thought you were just trying to load a jpg, which should work fine.

However, I see that you are using `javax.imageio`, which is part of java.desktop. The error you have posted is related to missing native method `com.sun.imageio.plugins.jpeg.JPEGImageReader.initJPEGImageReader`, which belongs to `libjavajpeg.a`. However, there is no static version of that library, only `libjavajpeg.dylib`. 

This means that in order to make this work you will have to build the JDK static version first of that library, then add it to Substrate list (https://github.com/gluonhq/substrate/blob/master/src/main/java/com/gluonhq/substrate/target/MacOSTargetConfiguration.java#L49).

Alternatively, you will have to get rid of this functionality (...), or move it to JavaFX (...).

**Comment by mipastgt** [comment]
Getting rid of this functionality is not an option, so I opted for an external library which can directly read the JPEG metadata and which also works with Substrate. Interestingly the same thing works for PNGs without problem.

**Comment by jperedadnr** [comment]
I'm closing this issue (it is still part of the no AWT support on Mac).
