### ISSUE TITLE
Exception: Values in form parameters can't be null -- was null for key sseIdentifier

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/substrate#500]
This exception is thrown when running Comments on Android:

```
[SUB] D/GraalCompiled(21058): Exception in thread "GluonCloudListDataReaderImpl#comments" 
[SUB] D/GraalCompiled(21058): java.lang.IllegalArgumentException: Values in form parameters can't be null -- was null for key sseIdentifier
[SUB] D/GraalCompiled(21058): 
[SUB] D/GraalCompiled(21058):   at com.gluonhq.connect.source.RestDataSource.createRequest(RestDataSource.java:496)
[SUB] D/GraalCompiled(21058): 
[SUB] D/GraalCompiled(21058):   at com.gluonhq.connect.source.RestDataSource.createInputStream(RestDataSource.java:511)
[SUB] D/GraalCompiled(21058): 
[SUB] D/GraalCompiled(21058):   at com.gluonhq.connect.source.RestDataSource.getInputStream(RestDataSource.java:93)
[SUB] D/GraalCompiled(21058): 
[SUB] D/GraalCompiled(21058):   at com.gluonhq.impl.cloudlink.client.data.GluonCloudListDataReaderImpl.readRestDataSource(GluonCloudListDataReaderImpl.java:28
[SUB] D/GraalCompiled(21058): 2)
[SUB] D/GraalCompiled(21058): 
[SUB] D/GraalCompiled(21058):   at com.gluonhq.impl.cloudlink.client.data.GluonCloudListDataReaderImpl.lambda$finalIterator$4(GluonCloudListDataReaderImpl.jav
[SUB] D/GraalCompiled(21058): a:219)
[SUB] D/GraalCompiled(21058): 
[SUB] D/GraalCompiled(21058):   at java.lang.Thread.run(Thread.java:834)
[SUB] D/GraalCompiled(21058): 
[SUB] D/GraalCompiled(21058):   at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:515)
[SUB] D/GraalCompiled(21058): 
[SUB] D/GraalCompiled(21058):   at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

**Comment by johanvos** [comment]
not substrate related
