### ISSUE TITLE
Run fails after successful gradle nativeBuild

### ISSUE THREAD

**Issue by phamvanthanh** [gluonhq/substrate#594]
Hi
It was fine when build with maven but this is what I got when build with gradle.

PS F:\client-samples-master\Maven\HelloFX\build\client\x86_64-windows> .\hellofx
Exception in thread "main" java.lang.RuntimeException: Application launch error
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:202)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
        at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)
Caused by: java.lang.AssertionError: java.lang.ClassNotFoundException: javafx.scene.image.Image
        at com.sun.javafx.util.Utils.forceInit(Utils.java:858)
        at com.sun.javafx.tk.Toolkit.<clinit>(Toolkit.java:944)
        at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
        at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
        at java.lang.Class.ensureInitialized(DynamicHub.java:499)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        ... 3 more
Caused by: java.lang.ClassNotFoundException: javafx.scene.image.Image
        at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
        at java.lang.Class.forName(DynamicHub.java:1207)
        at com.sun.javafx.util.Utils.forceInit(Utils.java:855)
        ... 12 more

**Comment by phamvanthanh** [comment]
This is the build file

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id 'java'
    id 'application'
    id "org.openjfx.javafxplugin" version "0.0.7"
    id 'com.gluonhq.client-gradle-plugin' version '0.1.23'
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = uri('http://repo.maven.apache.org/maven2')
    }
    maven {
        url "https://plugins.gradle.org/m2/"
    }
    maven {
        url = uri('http://nexus.gluonhq.com/nexus/content/repositories/releases/')
    }
}

javafx {
    version = "14"
    modules = [ 'javafx.controls' ]
}



group = 'hello'
version = '1.0-SNAPSHOT'
description = 'hellofx'
sourceCompatibility = '11'

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

mainClassName = 'hellofx.HelloFX'
