### ISSUE TITLE
java.lang.NoSuchMethodException

### ISSUE THREAD

**Issue by Plantrek** [gluonhq/substrate#613]
Hi
I do not know this is because of Graalvm or subtrate.
What should I do?
[java.lang.NoSuchMethodException: com.sun.xml.bind.v2.ContextFactory.createContext([Ljava.lang.Class;, java.util.Map)]
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:259)
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:240)
        at javax.xml.bind.ContextFinder.find(ContextFinder.java:363)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:632)
         at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
        at java.security.AccessController.doPrivileged(AccessController.java:101)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_Runnable_2_0002erun_00028_00029V(JNIJavaCallWrappers.java:0)
        at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
        at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)
Caused by: java.lang.NoSuchMethodException: com.sun.xml.bind.v2.ContextFactory.createContext([Ljava.lang.Class;, java.util.Map)
        at java.lang.Class.getMethod(DynamicHub.java:1036)
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:249)

**Comment by jperedadnr** [comment]
This is usually a reflection case. You have to add the necessary class to the reflection list. See https://docs.gluonhq.com/client/#_reflectionlist

**Comment by Plantrek** [comment]
@jperedadnr 
I believe the problem subjects to ServiceLoader. How to enable ServiceLoader or where to place arguments to the build. I have tried with no lucks
