### ISSUE TITLE
com.oracle.svm.core.jdk.UnsupportedFeatureError: ObjectInputStream.readObject()

### ISSUE THREAD

**Issue by phamvanthanh** [gluonhq/substrate#626]
Hi
Does this mean Graalvm implementation or configuration?

This happened at run time
Os Windows 10
Graalvm 20.2.0

com.oracle.svm.core.jdk.UnsupportedFeatureError: ObjectInputStream.readObject()

Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273)
        at com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83)
        at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1786)
        ... 32 more
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: ObjectInputStream.readObject()
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:86)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:53)

**Comment by mipastgt** [comment]
GraalVM/native-image currently does not support any kind of Java serialization. See: https://github.com/oracle/graal/blob/master/substratevm/LIMITATIONS.md#serialization

I recently stumbled of the the same problem and had to find another serialization mechanism which of course is not possible if you do not have control over the relevant piece of software.

**Comment by phamvanthanh** [comment]
@mipastgt 
Thanks for your sharing. I though about XML or Json but It would be quite a lot of changes  and the problem of arbitrary access to any cluster of database would be harder.

I am a little confused about replacement of Serialization mechanism or continue supporting in GraalVM as works of this seems to be in progress https://github.com/oracle/graal/issues/460

**Comment by mipastgt** [comment]
Well, this is 'in progrees' already for two years :-( As a quick and dirty solution I used Jackson because I needed a working solution now but in the long run I am planning to use Googles protocol buffers but have not tried that yet. I hope I do not stumble into the same isssues there. At least Jackson worked for me so far.

**Comment by jperedadnr** [comment]
Serialization is supported by GraalVM. Running `mvn gluonfx:runagent` should create the required configuration files.
