### ISSUE TITLE
Orientation change causes app dying

### ISSUE THREAD

**Issue by KMUS** [gluonhq/substrate#653]
A slightly modified HelloGluon sample always dies if orientation is changed to horizontal or vertical. Tested with MEmu Android 7.1 64 bit emulator.

```
javafx.version = 14.0.1
attach.version = 4.0.7
client.plugin.version = 0.1.27
GraalVM version = https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/20.2.0-dev-20200606_0217

```
```
06-06 16:33:46.064   108   211 D gralloc_gmin: gralloc_alloc: Creating ashmem region of size 8294400
06-06 16:33:46.076   108   108 E EGL_adreno: tid 108: eglCreateSyncKHR(2280): error 0x3004 (EGL_BAD_ATTRIBUTE)
06-06 16:33:46.092   108   108 E SurfaceFlinger: setOrientation, mFbdev=0x7fa69bc3d140, mFbDev->setOrientation=0x7fa69c838470, orientation=0
06-06 16:33:46.092   108   108 I gralloc_gmin: setOrientation: orientation=0
06-06 16:33:46.092   550   565 I ActivityManager: Config changes=480 {1.0 ?mcc?mnc [de_DE] ldltr sw600dp w600dp h1042dp 288dpi lrg long port finger qwerty/v/v -nav/h s.9}
06-06 16:33:46.093   550   590 I InputReader: Reconfiguring input devices.  changes=0x00000004
06-06 16:33:46.093   550   590 I InputReader: Device reconfigured: id=6, name='User Input', size 1080x1920, orientation 0, mode 1, display id 0
06-06 16:33:46.126  2712  2712 V GraalActivity: onPause
06-06 16:33:46.126  2712  2712 E GraalGluon: Dispatching lifecycle event from native Dalvik layer: pause
06-06 16:33:46.126  2712  2712 D GluonAttach: Call Attach method from native Lifecycle: pause
06-06 16:33:46.126  2712  2712 D GraalGluon: ATTACH_DALVIK, tid = 2712, existed? 1, dalvikEnv at 0x10014a20
06-06 16:33:46.126  2712  2712 D GraalGluon: DETACH_DALVIK, tid = 2712, existed = 1, env at 0x10014a20
06-06 16:33:46.126  2712  2712 D GluonAttach: called Attach method from native Lifecycle done
06-06 16:33:46.128  2712  2712 V GraalActivity: onStop
06-06 16:33:46.128  2712  2712 E GraalGluon: Dispatching lifecycle event from native Dalvik layer: stop
06-06 16:33:46.128  2712  2712 D GluonAttach: Call Attach method from native Lifecycle: stop
06-06 16:33:46.128  2712  2712 D GraalGluon: ATTACH_DALVIK, tid = 2712, existed? 1, dalvikEnv at 0x10014a20
06-06 16:33:46.128  2712  2712 D GraalGluon: DETACH_DALVIK, tid = 2712, existed = 1, env at 0x10014a20
06-06 16:33:46.128  2712  2712 D GluonAttach: called Attach method from native Lifecycle done
06-06 16:33:46.128  2712  2712 V GraalActivity: onDestroy
06-06 16:33:46.128  2712  2712 E GraalGluon: Dispatching lifecycle event from native Dalvik layer: destroy
06-06 16:33:46.128  2712  2712 D GluonAttach: Call Attach method from native Lifecycle: destroy
06-06 16:33:46.128  2712  2712 D GraalGluon: ATTACH_DALVIK, tid = 2712, existed? 1, dalvikEnv at 0x10014a20
06-06 16:33:46.128  2712  2712 D GraalGluon: DETACH_DALVIK, tid = 2712, existed = 1, env at 0x10014a20
06-06 16:33:46.128  2712  2712 D GluonAttach: called Attach method from native Lifecycle done
06-06 16:33:46.128  2712  2712 I Process : Sending signal. PID: 2712 SIG: 9
06-06 16:33:46.148   550   589 W InputDispatcher: channel '1fdbf83 com.example.jfxnative/com.gluonhq.helloandroid.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
06-06 16:33:46.148   550   589 E InputDispatcher: channel '1fdbf83 com.example.jfxnative/com.gluonhq.helloandroid.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
06-06 16:33:46.151   550  2101 D GraphicsStats: Buffer count: 4
06-06 16:33:46.151   550  1746 I ActivityManager: Process com.example.jfxnative (pid 2712) has died
06-06 16:33:46.151   550  1746 D ActivityManager: cleanUpApplicationRecord -- 2712
06-06 16:33:46.152   550  1746 W ActivityManager: Force removing ActivityRecord{4517391 u0 com.example.jfxnative/com.gluonhq.helloandroid.MainActivity t64}: app died, no saved state
06-06 16:33:46.160   550  2707 I WindowManager: WIN DEATH: Window{1fdbf83 u0 com.example.jfxnative/com.gluonhq.helloandroid.MainActivity}
06-06 16:33:46.160   550  2707 W InputDispatcher: Attempted to unregister already unregistered input channel '1fdbf83 com.example.jfxnative/com.gluonhq.helloandroid.MainActivity (server)'
06-06 16:33:46.160   550  2707 W WindowManager: Force-removing child win Window{e3ffcd7 u0 SurfaceView - com.example.jfxnative/com.gluonhq.helloandroid.MainActivity} from container Window{1fdbf83 u0 com.example.jfxnative/com.gluonhq.helloandroid.MainActivity}
06-06 16:33:46.166   550   701 W WindowManager: Failed looking up window
06-06 16:33:46.166   550   701 W WindowManager: java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@bb6a500 does not exist
06-06 16:33:46.166   550   701 W WindowManager:         at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9439)
06-06 16:33:46.166   550   701 W WindowManager:         at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9430)
06-06 16:33:46.166   550   701 W WindowManager:         at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1807)
06-06 16:33:46.166   550   701 W WindowManager:         at android.os.BinderProxy.sendDeathNotice(Binder.java:688)
06-06 16:33:46.166   550   701 I WindowManager: WIN DEATH: null
06-06 16:33:46.170   550  1746 W SchedPolicy: add_tid_to_cgroup failed to write '1080' (Permission denied); fd=4
06-06 16:33:46.191   550  2676 W SchedPolicy: add_tid_to_cgroup failed to write '1161' (Permission denied); fd=4
06-06 16:33:46.193   550   562 W SchedPolicy: add_tid_to_cgroup failed to write '1161' (Permission denied); fd=24
06-06 16:33:46.225   550   561 W ActivityManager: Unable to start service Intent { act=com.nicai.intent.action.INIT_DEVELOPER cmp=com.dev.developer/com.test.tools.ui.MyService } U=0: not found
06-06 16:33:46.232  1080  2831 D DynamitePackage: Instantiating com.google.android.gms.ads.ChimeraAdLoaderBuilderCreatorImpl
06-06 16:33:46.249  1080  2831 D DynamitePackage: Instantiating com.google.android.gms.ads.ChimeraAdLoaderBuilderCreatorImpl
06-06 16:33:46.291   550   701 W SchedPolicy: add_tid_to_cgroup failed to write '1433' (Permission denied); fd=24
06-06 16:33:46.309   550   571 I WindowManager: Screen frozen for +246ms due to Window{d514cd u0 com.android.systemui.ImageWallpaper}
06-06 16:33:46.373  1080  1180 E Launcher.Model: Missing Application on load: AppInfo [intent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.microvirt.launcher2/com.microvirt.launcher.Launcher }, iconBitmap=android.graphics.Bitmap@8c451af, firstInstallTime=1567664849000, componentName=ComponentInfo{com.microvirt.launcher2/com.microvirt.launcher.Launcher}, flags=0, id=-1, itemType=0, container=-1, screenId=-1, cellX=-1, cellY=-1, spanX=1, spanY=1, minSpanX=1, minSpanY=1, requiresDbUpdate=false, title=MEmu Launcher2, dropPos=null]
06-06 16:33:48.323   550   571 I art     : Starting a blocking GC Explicit
06-06 16:33:48.336   550   571 I art     : Explicit concurrent mark sweep GC freed 28848(2MB) AllocSpace objects, 37(740KB) LOS objects, 33% free, 9MB/13MB, paused 331us total 12.598ms
06-06 16:33:51.327  1080  1396 W ConnectionTracker: Exception thrown while unbinding
06-06 16:33:51.327  1080  1396 W ConnectionTracker: java.lang.IllegalArgumentException: Service not registered: lm@ff3e3fc
06-06 16:33:51.327  1080  1396 W ConnectionTracker:     at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1289)
06-06 16:33:51.327  1080  1396 W ConnectionTracker:     at android.app.ContextImpl.unbindService(ContextImpl.java:1483)
06-06 16:33:51.327  1080  1396 W ConnectionTracker:     at android.content.ContextWrapper.unbindService(ContextWrapper.java:648)
06-06 16:33:51.327  1080  1396 W ConnectionTracker:     at ce.b(:com.google.android.gms.dynamite_measurementdynamite@201817056@20.18.17 (040800-0):1)
06-06 16:33:51.327  1080  1396 W ConnectionTracker:     at ce.a(:com.google.android.gms.dynamite_measurementdynamite@201817056@20.18.17 (040800-0):5)
06-06 16:33:51.327  1080  1396 W ConnectionTracker:     at ln.A(:com.google.android.gms.dynamite_measurementdynamite@201817056@20.18.17 (040800-0):10)
06-06 16:33:51.327  1080  1396 W ConnectionTracker:     at ky.a(:com.google.android.gms.dynamite_measurementdynamite@201817056@20.18.17 (040800-0):3)
06-06 16:33:51.327  1080  1396 W ConnectionTracker:     at dy.run(:com.google.android.gms.dynamite_measurementdynamite@201817056@20.18.17 (040800-0):2)
06-06 16:33:51.327  1080  1396 W ConnectionTracker:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
06-06 16:33:51.327  1080  1396 W ConnectionTracker:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-06 16:33:51.327  1080  1396 W ConnectionTracker:     at iw.run(:com.google.android.gms.dynamite_measurementdynamite@201817056@20.18.17 (040800-0):15)
```

**Comment by jperedadnr** [comment]
See this [thread](https://stackoverflow.com/questions/11420963/app-dies-with-sending-signal-but-no-exception-or-other-info), looks like a memory issue, based on:

> Process : Sending signal. PID: 2712 SIG: 9

Have you also tried on a real device?

Also, does the non-modified HelloGluon work? Does HelloFX work?

**Comment by KMUS** [comment]
@jperedadnr 

Sorry, no ARM64 devices available at the moment.
Both samples do not work and have the same issue as the first one.

HelloFX

```
06-06 23:26:54.408   106   801 D gralloc_gmin: gralloc_alloc: Creating ashmem region of size 8294400
06-06 23:26:54.421   106   106 E EGL_adreno: tid 106: eglCreateSyncKHR(2280): error 0x3004 (EGL_BAD_ATTRIBUTE)
06-06 23:26:54.429   106   106 E SurfaceFlinger: setOrientation, mFbdev=0x7ff916a3d140, mFbDev->setOrientation=0x7ff917647470, orientation=3
06-06 23:26:54.429   106   106 I gralloc_gmin: setOrientation: orientation=3
06-06 23:26:54.429   551   567 I ActivityManager: Config changes=480 {1.0 ?mcc?mnc [de_DE] ldltr sw600dp w1066dp h576dp 288dpi lrg long land finger qwerty/v/v -nav/h s.10}
06-06 23:26:54.431   551   609 I InputReader: Reconfiguring input devices.  changes=0x00000004
06-06 23:26:54.431   551   609 I InputReader: Device reconfigured: id=6, name='User Input', size 1080x1920, orientation 3, mode 1, display id 0
06-06 23:26:54.444   106   106 W SurfaceFlinger: couldn't log to binary event log: overflow.
06-06 23:26:54.461  2831  2831 V GraalActivity: onPause
06-06 23:26:54.461  2831  2831 E GraalGluon: Dispatching lifecycle event from native Dalvik layer: pause
06-06 23:26:54.464  2831  2831 V GraalActivity: onStop
06-06 23:26:54.464  2831  2831 E GraalGluon: Dispatching lifecycle event from native Dalvik layer: stop
06-06 23:26:54.464  2831  2831 V GraalActivity: onDestroy
06-06 23:26:54.464  2831  2831 E GraalGluon: Dispatching lifecycle event from native Dalvik layer: destroy
06-06 23:26:54.464  2831  2831 I Process : Sending signal. PID: 2831 SIG: 9
06-06 23:26:54.502   551   608 W InputDispatcher: channel '150bbcf hello.hellofx/com.gluonhq.helloandroid.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
06-06 23:26:54.502   551   608 E InputDispatcher: channel '150bbcf hello.hellofx/com.gluonhq.helloandroid.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
06-06 23:26:54.502   551  4759 D GraphicsStats: Buffer count: 4
06-06 23:26:54.502   551  2144 I WindowManager: WIN DEATH: Window{150bbcf u0 hello.hellofx/com.gluonhq.helloandroid.MainActivity}
06-06 23:26:54.502   551  2144 W InputDispatcher: Attempted to unregister already unregistered input channel '150bbcf hello.hellofx/com.gluonhq.helloandroid.MainActivity (server)'
06-06 23:26:54.502   551  2144 W WindowManager: Force-removing child win Window{be26bfa u0 SurfaceView - hello.hellofx/com.gluonhq.helloandroid.MainActivity} from container Window{150bbcf u0 hello.hellofx/com.gluonhq.helloandroid.MainActivity}
06-06 23:26:54.502   551  2302 I ActivityManager: Process hello.hellofx (pid 2831) has died
06-06 23:26:54.502   551  2302 D ActivityManager: cleanUpApplicationRecord -- 2831
06-06 23:26:54.503   551  2302 W ActivityManager: Force removing ActivityRecord{bdad7e7 u0 hello.hellofx/com.gluonhq.helloandroid.MainActivity t73}: app died, no saved state
06-06 23:26:54.507   551  4445 W WindowManager: Failed looking up window
06-06 23:26:54.507   551  4445 W WindowManager: java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@9b3395c does not exist
06-06 23:26:54.507   551  4445 W WindowManager:         at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9439)
06-06 23:26:54.507   551  4445 W WindowManager:         at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9430)
06-06 23:26:54.507   551  4445 W WindowManager:         at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1807)
06-06 23:26:54.507   551  4445 W WindowManager:         at android.os.BinderProxy.sendDeathNotice(Binder.java:688)
06-06 23:26:54.507   551  4445 I WindowManager: WIN DEATH: null
06-06 23:26:54.516   551  2302 W SchedPolicy: add_tid_to_cgroup failed to write '1462' (Permission denied); fd=4
06-06 23:26:54.536  1462  1462 D AppCompatDelegate: Application config ({1.0 ?mcc?mnc [de_DE] ldltr sw600dp w1066dp h576dp 288dpi lrg long land finger qwerty/v/v -nav/h s.10}) matches base context config, using empty base overlay
06-06 23:26:54.536  1462  1462 D AppCompatDelegate: Applying night mode using ContextThemeWrapper and applyOverrideConfiguration(). Config: {0.0 ?mcc?mnc ?localeList ?layoutDir ?swdp ?wdp ?hdp ?density ?lsize ?long ?orien ?uimode ?touch ?keyb/?/? ?nav/?}
06-06 23:26:54.539  1462  1462 D AppCompatDelegate: updateForNightMode [allowRecreation:false, currentNightMode:16, newNightMode:16, activityHandlingUiMode:false, baseContextAttached:true, created:false, canReturnDifferentContext:true, host:com.google.android.finsky.unauthenticated.UnauthenticatedMainActivity@5dd86af]
06-06 23:26:54.539  1462  1462 D AppCompatDelegate: updateForNightMode not recreating Activity: com.google.android.finsky.unauthenticated.UnauthenticatedMainActivity@5dd86af
06-06 23:26:54.539  1462  1462 D AppCompatDelegate: updateForNightMode. Skipping. Night mode: 1 for host:com.google.android.finsky.unauthenticated.UnauthenticatedMainActivity@5dd86af
06-06 23:26:54.541  1462  1462 I Finsky  : [1] jba.c(2): Account name null when calculating account hash
06-06 23:26:54.549  1462  1462 W ProxyAndroidLoggerBackend: Too many Flogger logs received before configuration. Dropping old logs.
06-06 23:26:54.558  1462  1462 D AppCompatDelegate: updateForNightMode [allowRecreation:true, currentNightMode:16, newNightMode:16, activityHandlingUiMode:false, baseContextAttached:true, created:true, canReturnDifferentContext:true, host:com.google.android.finsky.unauthenticated.UnauthenticatedMainActivity@5dd86af]
06-06 23:26:54.558  1462  1462 D AppCompatDelegate: updateForNightMode not recreating Activity: com.google.android.finsky.unauthenticated.UnauthenticatedMainActivity@5dd86af
06-06 23:26:54.558  1462  1462 D AppCompatDelegate: updateForNightMode. Skipping. Night mode: 1 for host:com.google.android.finsky.unauthenticated.UnauthenticatedMainActivity@5dd86af
06-06 23:26:54.631   551   573 I WindowManager: Screen frozen for +224ms due to Window{e7817a1 u0 com.android.vending/com.google.android.finsky.unauthenticated.UnauthenticatedMainActivity}
```
HelloGluon

```
06-06 23:28:13.514  1462  1522 I PlayCommon: [49] aoib.c(26): Preparing logs for uploading
06-06 23:28:13.515  1462  1522 W PlayCommon: [49] aoib.a(1): No account for auth token provided
06-06 23:28:13.515  1462  1522 I PlayCommon: [49] aoib.c(201): Connecting to server: https://play.googleapis.com/play/log?format=raw&proto_v2=true
06-06 23:28:13.674  1462  1522 I PlayCommon: [49] aoib.c(232): Successfully uploaded logs.
06-06 23:28:14.775   106   803 D gralloc_gmin: gralloc_alloc: Creating ashmem region of size 8294400
06-06 23:28:14.786   106   106 E EGL_adreno: tid 106: eglCreateSyncKHR(2280): error 0x3004 (EGL_BAD_ATTRIBUTE)
06-06 23:28:14.795   106   106 E SurfaceFlinger: setOrientation, mFbdev=0x7ff916a3d140, mFbDev->setOrientation=0x7ff917647470, orientation=0
06-06 23:28:14.795   106   106 I gralloc_gmin: setOrientation: orientation=0
06-06 23:28:14.796   551   567 I ActivityManager: Config changes=480 {1.0 ?mcc?mnc [de_DE] ldltr sw600dp w600dp h1042dp 288dpi lrg long port finger qwerty/v/v -nav/h s.11}
06-06 23:28:14.799   551   609 I InputReader: Reconfiguring input devices.  changes=0x00000004
06-06 23:28:14.799   551   609 I InputReader: Device reconfigured: id=6, name='User Input', size 1080x1920, orientation 0, mode 1, display id 0
06-06 23:28:14.811   106   106 W SurfaceFlinger: couldn't log to binary event log: overflow.
06-06 23:28:14.829  5427  5427 V GraalActivity: onPause
06-06 23:28:14.829  5427  5427 E GraalGluon: Dispatching lifecycle event from native Dalvik layer: pause
06-06 23:28:14.829  5427  5427 D GluonAttach: Call Attach method from native Lifecycle: pause
06-06 23:28:14.829  5427  5427 D GraalGluon: ATTACH_DALVIK, tid = 5427, existed? 1, dalvikEnv at 0x10014a20
06-06 23:28:14.829  5427  5427 D GluonAttach: Call2 Attach method from native Lifecycle: pause, class at 0x10075e and method at 0x7fb204efbbd8 and jc at 0x1d
06-06 23:28:14.829  5427  5427 D GluonAttach: Call3 Attach method from native Lifecycle: pause
06-06 23:28:14.830  5427  5427 D GluonAttach: Call4 Attach method from native Lifecycle: pause
06-06 23:28:14.830  5427  5427 D GraalGluon: DETACH_DALVIK, tid = 5427, existed = 1, env at 0x10014a20
06-06 23:28:14.830  5427  5427 D GluonAttach: called Attach method from native Lifecycle done
06-06 23:28:14.833  5427  5427 V GraalActivity: onStop
06-06 23:28:14.833  5427  5427 E GraalGluon: Dispatching lifecycle event from native Dalvik layer: stop
06-06 23:28:14.833  5427  5427 D GluonAttach: Call Attach method from native Lifecycle: stop
06-06 23:28:14.833  5427  5427 D GraalGluon: ATTACH_DALVIK, tid = 5427, existed? 1, dalvikEnv at 0x10014a20
06-06 23:28:14.833  5427  5427 D GluonAttach: Call2 Attach method from native Lifecycle: stop, class at 0x10075e and method at 0x7fb204efbbd8 and jc at 0x20001d
06-06 23:28:14.833  5427  5427 D GluonAttach: Call3 Attach method from native Lifecycle: stop
06-06 23:28:14.833  5427  5427 D GluonAttach: Call4 Attach method from native Lifecycle: stop
06-06 23:28:14.833  5427  5427 D GraalGluon: DETACH_DALVIK, tid = 5427, existed = 1, env at 0x10014a20
06-06 23:28:14.833  5427  5427 D GluonAttach: called Attach method from native Lifecycle done
06-06 23:28:14.833  5427  5427 V GraalActivity: onDestroy
06-06 23:28:14.834  5427  5427 E GraalGluon: Dispatching lifecycle event from native Dalvik layer: destroy
06-06 23:28:14.834  5427  5427 D GluonAttach: Call Attach method from native Lifecycle: destroy
06-06 23:28:14.834  5427  5427 D GraalGluon: ATTACH_DALVIK, tid = 5427, existed? 1, dalvikEnv at 0x10014a20
06-06 23:28:14.834  5427  5427 D GluonAttach: Call2 Attach method from native Lifecycle: destroy, class at 0x10075e and method at 0x7fb204efbbd8 and jc at 0x10001d
06-06 23:28:14.834  5427  5427 D GluonAttach: Call3 Attach method from native Lifecycle: destroy
06-06 23:28:14.834  5427  5427 D GluonAttach: Call4 Attach method from native Lifecycle: destroy
06-06 23:28:14.834  5427  5427 D GraalGluon: DETACH_DALVIK, tid = 5427, existed = 1, env at 0x10014a20
06-06 23:28:14.834  5427  5427 D GluonAttach: called Attach method from native Lifecycle done
06-06 23:28:14.834  5427  5427 I Process : Sending signal. PID: 5427 SIG: 9
06-06 23:28:14.867   551   608 W InputDispatcher: channel 'd1306e7 com.gluonhq.hello.hellogluon/com.gluonhq.helloandroid.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
06-06 23:28:14.867   551   608 E InputDispatcher: channel 'd1306e7 com.gluonhq.hello.hellogluon/com.gluonhq.helloandroid.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
06-06 23:28:14.870   551  4445 D GraphicsStats: Buffer count: 4
06-06 23:28:14.870   551  2143 I ActivityManager: Process com.gluonhq.hello.hellogluon (pid 5427) has died
06-06 23:28:14.870   551  2143 D ActivityManager: cleanUpApplicationRecord -- 5427
06-06 23:28:14.870   551  2143 W ActivityManager: Force removing ActivityRecord{8403691 u0 com.gluonhq.hello.hellogluon/com.gluonhq.helloandroid.MainActivity t77}: app died, no saved state
06-06 23:28:14.872   551   563 I WindowManager: WIN DEATH: Window{d1306e7 u0 com.gluonhq.hello.hellogluon/com.gluonhq.helloandroid.MainActivity}
06-06 23:28:14.872   551   563 W InputDispatcher: Attempted to unregister already unregistered input channel 'd1306e7 com.gluonhq.hello.hellogluon/com.gluonhq.helloandroid.MainActivity (server)'
06-06 23:28:14.872   551   563 W WindowManager: Force-removing child win Window{2ec6e2 u0 SurfaceView - com.gluonhq.hello.hellogluon/com.gluonhq.helloandroid.MainActivity} from container Window{d1306e7 u0 com.gluonhq.hello.hellogluon/com.gluonhq.helloandroid.MainActivity}
06-06 23:28:14.877   551  2144 W WindowManager: Failed looking up window
06-06 23:28:14.877   551  2144 W WindowManager: java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@ade8294 does not exist
06-06 23:28:14.877   551  2144 W WindowManager:         at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9439)
06-06 23:28:14.877   551  2144 W WindowManager:         at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9430)
06-06 23:28:14.877   551  2144 W WindowManager:         at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1807)
06-06 23:28:14.877   551  2144 W WindowManager:         at android.os.BinderProxy.sendDeathNotice(Binder.java:688)
06-06 23:28:14.877   551  2144 I WindowManager: WIN DEATH: null
06-06 23:28:14.880   551  2143 W SchedPolicy: add_tid_to_cgroup failed to write '1078' (Permission denied); fd=4
06-06 23:28:14.880   551  2143 I ActivityManager: Killing 1140:com.google.process.gapps/u0a16 (adj 906): empty #6
06-06 23:28:14.893   551  2623 D ActivityManager: cleanUpApplicationRecord -- 1140
06-06 23:28:14.912   551   563 W SchedPolicy: add_tid_to_cgroup failed to write '1254' (Permission denied); fd=4
06-06 23:28:14.913   551  5243 W SchedPolicy: add_tid_to_cgroup failed to write '1254' (Permission denied); fd=24
06-06 23:28:14.946   551   562 W ActivityManager: Unable to start service Intent { act=com.nicai.intent.action.INIT_DEVELOPER cmp=com.dev.developer/com.test.tools.ui.MyService } U=0: not found
06-06 23:28:14.956   551  2633 W SchedPolicy: add_tid_to_cgroup failed to write '1194' (Permission denied); fd=4
06-06 23:28:14.977  1078  5525 D DynamitePackage: Instantiating com.google.android.gms.ads.ChimeraAdLoaderBuilderCreatorImpl
06-06 23:28:14.984  1078  5525 D DynamitePackage: Instantiating com.google.android.gms.ads.ChimeraAdLoaderBuilderCreatorImpl
06-06 23:28:15.046   551   573 I WindowManager: Screen frozen for +273ms due to Window{f9d3645 u0 com.android.systemui.ImageWallpaper}
06-06 23:28:15.143  1078  1188 E Launcher.Model: Missing Application on load: AppInfo [intent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.microvirt.launcher2/com.microvirt.launcher.Launcher }, iconBitmap=android.graphics.Bitmap@138158b, firstInstallTime=1567664849000, componentName=ComponentInfo{com.microvirt.launcher2/com.microvirt.launcher.Launcher}, flags=0, id=-1, itemType=0, container=-1, screenId=-1, cellX=-1, cellY=-1, spanX=1, spanY=1, minSpanX=1, minSpanY=1, requiresDbUpdate=false, title=MEmu Launcher2, dropPos=null]
06-06 23:28:17.057   551   573 I art     : Starting a blocking GC Explicit
06-06 23:28:17.068   551   573 I art     : Explicit concurrent mark sweep GC freed 7720(551KB) AllocSpace objects, 4(92KB) LOS objects, 33% free, 9MB/13MB, paused 134us total 10.831ms
06-06 23:28:20.069  1078  5233 W ConnectionTracker: Exception thrown while unbinding
06-06 23:28:20.069  1078  5233 W ConnectionTracker: java.lang.IllegalArgumentException: Service not registered: lm@b27a8e0
06-06 23:28:20.069  1078  5233 W ConnectionTracker:     at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1289)
06-06 23:28:20.069  1078  5233 W ConnectionTracker:     at android.app.ContextImpl.unbindService(ContextImpl.java:1483)
06-06 23:28:20.069  1078  5233 W ConnectionTracker:     at android.content.ContextWrapper.unbindService(ContextWrapper.java:648)
06-06 23:28:20.069  1078  5233 W ConnectionTracker:     at ce.b(:com.google.android.gms.dynamite_measurementdynamite@201817056@20.18.17 (040800-0):1)
06-06 23:28:20.069  1078  5233 W ConnectionTracker:     at ce.a(:com.google.android.gms.dynamite_measurementdynamite@201817056@20.18.17 (040800-0):5)
06-06 23:28:20.069  1078  5233 W ConnectionTracker:     at ln.A(:com.google.android.gms.dynamite_measurementdynamite@201817056@20.18.17 (040800-0):10)
06-06 23:28:20.069  1078  5233 W ConnectionTracker:     at ky.a(:com.google.android.gms.dynamite_measurementdynamite@201817056@20.18.17 (040800-0):3)
06-06 23:28:20.069  1078  5233 W ConnectionTracker:     at dy.run(:com.google.android.gms.dynamite_measurementdynamite@201817056@20.18.17 (040800-0):2)
06-06 23:28:20.069  1078  5233 W ConnectionTracker:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
06-06 23:28:20.069  1078  5233 W ConnectionTracker:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-06 23:28:20.069  1078  5233 W ConnectionTracker:     at iw.run(:com.google.android.gms.dynamite_measurementdynamite@201817056@20.18.17 (040800-0):15)
06-06 23:28:21.144   551   551 I ActivityManager: Start proc 5547:com.android.vending:instant_app_installer/u0a25 for service com.android.vending/com.google.android.finsky.instantapps.metrics.LogFlushJob
```

**Comment by mipastgt** [comment]
On my Samsung phone and tablet this works like a charm.

**Comment by KMUS** [comment]
I have tried the last commit (4b4c16d) of Attach 4.0.8-SNAPSHOT and it has not changed anything.

**Comment by mipastgt** [comment]
I removed my previous edit above because I made a mistake. I now have orientation changes working on my phone as well as on my tablet again. In case you are tracking width and height you have to consider the fact that changing these two is not an atomic action.

**Comment by KMUS** [comment]
Tested it on a real Samsung Android 8.x device today and it works there but it should work on any common emulator too.
The test application uses JFoenix controls like JFXButton, JFXSlider, JFXSpinner, JFXTextField and FloatingActionButton. The controls on Linux and Windows are fast as expected except on Android. The user experience is bad there compared to an Android or web app.

**Comment by jperedadnr** [comment]
Substrate doesn't officially support Android emulators. Closing as not an issue.
