### ISSUE TITLE
Build Failure. ClassNotFoundException: org.apache.log4j.Priority

### ISSUE THREAD

**Issue by KopeMorta** [gluonhq/substrate#683]
I have problem with compiling my app with next error:

```
Fatal error:java.lang.NoClassDefFoundError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:465)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:346)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:505)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:114)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:534)
Caused by: java.lang.NoClassDefFoundError: org/apache/log4j/Priority
	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.CompilerToVM.getDeclaredMethods(Native Method)
	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotResolvedObjectTypeImpl.getDeclaredMethods(HotSpotResolvedObjectTypeImpl.java:958)
	at com.oracle.svm.jni.access.JNIAccessibleMethod.anyMatchIgnoreReturnType(JNIAccessibleMethod.java:139)
	at com.oracle.svm.jni.access.JNIAccessibleMember.findHidingSubclasses(JNIAccessibleMember.java:103)
	at com.oracle.svm.jni.access.JNIAccessibleMember.findHidingSubclasses(JNIAccessibleMember.java:110)
	at com.oracle.svm.jni.access.JNIAccessibleMember.setHidingSubclasses(JNIAccessibleMember.java:83)
	at com.oracle.svm.jni.access.JNIAccessibleMethod.finishBeforeCompilation(JNIAccessibleMethod.java:135)
	at com.oracle.svm.jni.access.JNIAccessFeature.beforeCompilation(JNIAccessFeature.java:348)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$doRun$2(NativeImageGenerator.java:597)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:597)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:453)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Priority
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 18 more
```

And i have warning:
```
Warning: class initialization of class io.netty.util.internal.logging.Log4JLogger failed with exception java.lang.NoClassDefFoundError: org/apache/log4j/Priority. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=io.netty.util.internal.logging.Log4JLogger to explicitly request delayed initialization of this class.
```

It seemed to me that the problem was in my library that uses Netty. I decided to check it out. I made an empty project, added a dependency on the library and ran native-image -jar.
Everything went well, and the warning above was also present.

I also use micronaut and its nativeimage dependency. He also participated in a test project.

OS: KUbuntu 20.04
Java: 11
client-maven-plugin version: 0.1.27

**Comment by jperedadnr** [comment]
Have you tried adding to your pom the following dependencies?

```
         <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.28</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-jdk14</artifactId>
            <version>1.7.28</version>
        </dependency>
```

**Comment by jperedadnr** [comment]
Does this help? https://stackoverflow.com/a/51723704/3956070

**Comment by KopeMorta** [comment]
> Does this help? https://stackoverflow.com/a/51723704/3956070

No.
log4j2 (core / api) not contains package ```org.apache.log4j``` and class Priority too.
It's log4j class.


This build problem can fix with this dependency: (without exclusion - maven build fail)
```
<dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.15</version>
            <exclusions>
                <exclusion>
                    <groupId>com.sun.jmx</groupId>
                    <artifactId>jmxri</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.sun.jdmk</groupId>
                    <artifactId>jmxtools</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>javax.jms</groupId>
                    <artifactId>jms</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

But after compiling with this dependency .exe (executable file) not working. Doesn't even reach main method in Main class (sout as first line don't work).

**Comment by EvokeAngle** [comment]
`<reflectionList>
                      
                        <list>org.apache.log4j.Priority</list>
                        <list>org.apache.logging.log4j.message.DefaultFlowMessageFactory</list>
                        <list>org.apache.logging.log4j.core.impl.Log4jContextFactory</list>
                        <list>org.apache.logging.log4j.message.ParameterizedMessageFactory</list>
                        <list>org.apache.logging.log4j.core.util.ExecutorServices</list>
                    </reflectionList>`

**Comment by EvokeAngle** [comment]
`<reflectionList>
                        <list>org.apache.log4j.Priority</list>
                        <list>org.apache.logging.log4j.message.DefaultFlowMessageFactory</list>
                        <list>org.apache.logging.log4j.core.impl.Log4jContextFactory</list>
                        <list>org.apache.logging.log4j.message.ParameterizedMessageFactory</list>
                        <list>org.apache.logging.log4j.core.util.ExecutorServices</list>
                    </reflectionList>`

**Comment by KopeMorta** [comment]
> ```
>             `<reflectionList>
>                     <list>org.apache.log4j.Priority</list>
>                     <list>org.apache.logging.log4j.message.DefaultFlowMessageFactory</list>
>                     <list>org.apache.logging.log4j.core.impl.Log4jContextFactory</list>
>                     <list>org.apache.logging.log4j.message.ParameterizedMessageFactory</list>
>                     <list>org.apache.logging.log4j.core.util.ExecutorServices</list>
>                 </reflectionList>`
> ```

Thank you, with your help, I figured out where to look and completed it a little. Now it's building.

So.
For using log4j2 log in substrate vm we need:
1. add dependencylog4j (1):
```
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.15</version>
            <exclusions>
                <exclusion>
                    <groupId>com.sun.jmx</groupId>
                    <artifactId>jmxri</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.sun.jdmk</groupId>
                    <artifactId>jmxtools</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>javax.jms</groupId>
                    <artifactId>jms</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

2. add dependency disruptor (Can this be avoided?):
```
        <dependency>
            <groupId>com.lmax</groupId>
            <artifactId>disruptor</artifactId>
            <version>3.4.2</version>
        </dependency>
```

3. add native-image args:
```
                        <arg>--initialize-at-build-time=jdk.xml.internal.SecuritySupport</arg>
                        <arg>--initialize-at-run-time=io.netty.util.internal.logging.Log4JLogger</arg>
                        <arg>--initialize-at-build-time=com.sun.org.apache.xerces</arg>
                        <arg>--initialize-at-build-time=com.sun.xml.internal.stream.util.ThreadLocalBufferAllocator</arg>
                        <arg>--initialize-at-build-time=jdk.xml.internal.JdkXmlUtils</arg>
                        <arg>--initialize-at-build-time=com.sun.xml.internal.stream.util.ThreadLocalBufferAllocator</arg>
                        <arg>--initialize-at-build-time=com.sun.org.apache.xerces.internal.impl.XMLScanner</arg>
```

4. add reflection list:
```
                        <list>org.apache.log4j.Priority</list>
                        <list>org.apache.logging.log4j.message.DefaultFlowMessageFactory</list>
                        <list>org.apache.logging.log4j.core.impl.Log4jContextFactory</list>
                        <list>org.apache.logging.log4j.message.ParameterizedMessageFactory</list>
                        <list>org.apache.logging.log4j.core.util.ExecutorServices</list>
                        <list>com.lmax.disruptor.EventTranslatorVararg</list>
```


If it is possible to simplify it somehow, I would be glad to see it.



Now build is successful but .exe not work :) (just do nothing on start, main method not call) 
But that's another problem. Because I have already encountered it in several projects. I think need create one more issue. (if exists - get me link pls)

**Comment by jperedadnr** [comment]
Glad it builds now, I'll close this issue then.
