### ISSUE TITLE
Extend support for WebView on iOS

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/substrate#686]

**Comment by samyc1201** [comment]
@jperedadnr 

Does this ticket include the features of JavaFX webview for example "call java from javascript" and "call javascript from java"?

I encounter an issue here:

```
public static void registerJavascriptBridge(WebView webview) {

	webview.getEngine().getLoadWorker().stateProperty().addListener((ov, oldState, newState) -> {
		if (newState == Worker.State.SUCCEEDED) {
			JSObject window = (JSObject) webview.getEngine().executeScript("window");
			System.out.println("window : " + window);
			window.setMember("JavaBridge", javaBridge);

			if (!isMobile())
				webview.getEngine().executeScript(
						"console.log = function(message)\n" + "{\n" + "    JavaBridge.log(message);\n" + "};");
		}
	});

}
```

My `window` object is always null:

```
[Mon Aug 31 16:49:21 SGT 2020][INFO] [SUB] setSwapInterval(0)
[Mon Aug 31 16:49:21 SGT 2020][INFO] [SUB] Couldn't parse arguments. java.lang.NumberFormatException: For input string: ""
[Mon Aug 31 16:49:21 SGT 2020][INFO] [SUB] [JVDBG] Error, jsId = null for jsEventHandler
[Mon Aug 31 16:49:21 SGT 2020][INFO] [SUB] Couldn't parse arguments. java.lang.NumberFormatException: For input string: ""
[Mon Aug 31 16:49:21 SGT 2020][INFO] [SUB] window : null
[Mon Aug 31 16:49:21 SGT 2020][INFO] [SUB] Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
[Mon Aug 31 16:49:21 SGT 2020][INFO] [SUB]  at hellofx.HelloFX.lambda$registerJavascriptBridge$0(HelloFX.java:160)
[Mon Aug 31 16:49:21 SGT 2020][INFO] [SUB]  at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
[Mon Aug 31 16:49:21 SGT 2020][INFO] [SUB]  at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
[Mon Aug 31 16:49:21 SGT 2020][INFO] [SUB]  at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
[Mon Aug 31 16:49:21 SGT 2020][INFO] [SUB]  at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
[Mon Aug 31 16:49:21 SGT 2020][INFO] [SUB]  at javafx.beans.propertate(WebEngine.java:109)
[Mon Aug 31 16:49:21 SGT 2020][INFO] [SUB]  at javafx.scene.web.WebEngine.notifyLoadFinished(WebEngine.java:907)
[Mon Aug 31 16:49:21 SGT 2020][INFO] [SUB]  at javafx.scene.web.WebView.notifyLoadFinished(WebView.java:1116)
[Mon Aug 31 16:49:21 SGT 2020][INFO] [SUB]  at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Ljavafx_scene_web_WebView_2_0002enotifyLoadFinished_00028Ljava_lang_String_2Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
```

This code is working fine in desktop app as well. 

This is quite an important features actually, as it allows us to load whole web pages (reactjs/angularjs) in iOS. Is there any tentative date this feature will be added? Thanks.

**Comment by jperedadnr** [comment]
Yes, this should be supported. Work is in progress.
