### ISSUE TITLE
java.lang.ClassNotFoundException: javafx.scene.control.TableColumnBase

### ISSUE THREAD

**Issue by eiswind** [gluonhq/substrate#732]
I'm compiling on linux x86_64 with 
graalvm-ce-java11-20.2.0-dev
("com.gluonhq.client-gradle-plugin") version "0.1.29"
with openjfx at 15-ea+8

 and at runtime I get the following trace;

```
java.lang.AssertionError: java.lang.ClassNotFoundException: javafx.scene.control.TableColumnBase
 at com.sun.javafx.util.Utils.forceInit(Utils.java:868)
        at com.sun.javafx.scene.control.TableColumnBaseHelper.<clinit>(TableColumnBaseHelper.java:39)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:351)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:271)
        at javafx.scene.control.TableColumnBase.<clinit>(TableColumnBase.java:132)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:351)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:271)
        at java.lang.Class.ensureInitialized(DynamicHub.java:515)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:236)
        at de.eiswind.fxproto.client.user.UserView.<init>(UserView.kt:43)
```

UserView:43 is as Simple as
```
val emailCol = TableColumn<UserModel, String>("Email")
```

The only non default in my setup is a custom reflect config.json at META-INF/native-image
```
[
  {
    "name": "de.eiswind.fxproto.client.FxProtoClientApplication",
    "methods": [
      {
        "name": "<init>",
        "parameterTypes": []
      }
    ]
  }
]
```

Could it be that this confuses the build?

**Comment by jperedadnr** [comment]
Most of the JavaFX classes are added by the plugin to a reflection list. You can find it under `target/client/x88-64_linux/gvm`. If a given class, like `javafx.scene.control.TableColumnBase` is missing you can:

- Add it to the reflection list in your pom (see https://docs.gluonhq.com/client/#_reflectionlist):
```
<reflectionList>
    <item>javafx.scene.control.TableColumnBase</item>
</reflectionList>
```
- Add it to a reflectionconfig.json file under `META-INF/substrate/config/reflectionconfig.json` (see https://docs.gluonhq.com/client/#_jni_and_reflection):
```
{
    "name": "javafx.scene.control.TableColumnBase"
}
```
- Add it to your  custom reflect config.json at META-INF/native-image:
```
[
  {
    "name": "de.eiswind.fxproto.client.FxProtoClientApplication",
    "methods": [
      {
        "name": "<init>",
        "parameterTypes": []
      }
    ]
  }, 
  {
     "name": "javafx.scene.control.TableColumnBase"
  }
]
```

**Comment by eiswind** [comment]
Thanks for the input. This indeed did help.
Maybe you could add that to the built-in list?

**Comment by jperedadnr** [comment]
Sorry for the late reply.
Adding _all_ possible cases of JavaFX classes/methods that are being used via reflection will cause an increase in size as it will pull in many things that are not used by a given application.
While not a perfect solution, running `mvn gluonfx:runagent` is a better way to find out what is exactly needed, and that provides the extra cases that are not included in the built-in list.
