### ISSUE TITLE
Caused by: org.apache.commons.logging.LogConfigurationException: No suitable Log implementation

### ISSUE THREAD

**Issue by Shadow326159** [gluonhq/substrate#734]
I am using Unirest library. The program builds and runs, but the Unirest method fails. At first there were errors due to missing classes. I added them to ReflectionList.

```
<list> com.mashape.unirest.http.options.Options </list>
<list> org.apache.commons.logging.LogFactory </list> 
<list> org.apache.commons.logging.impl.LogFactoryImpl </list> 
<list> org.apache.commons.logging.LogConfigurationException </list>
```

Now only this remains.
Caused by: org.apache.commons.logging.LogConfigurationException: No suitable Log implementation

Full report.
```
[вт авг. 04 22:31:59 MSK 2020][INFO] ==================== RUN TASK ====================
[вт авг. 04 22:31:59 MSK 2020][FINE] PB Command for run until end: C:\Users\DMan\IdeaProjects\Calculator\target\client\x86_64-windows\Calculator.exe
[вт авг. 04 22:31:59 MSK 2020][FINE] Start process run until end...
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] Exception in thread "JavaFX Application Thread" java.lang.ExceptionInInitializerError
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:291)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:144)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:351)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:271)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.getDefaultRegistry(PoolingHttpClientConnectionManager.java:109)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:116)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.mashape.unirest.http.options.Options.refresh(Options.java:72)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.mashape.unirest.http.options.Options.<clinit>(Options.java:46)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:351)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:271)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.mashape.unirest.http.Unirest.setTimeouts(Unirest.java:91)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at org.dman.Controller.lambda$initialize$19(Controller.java:116)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at javafx.event.Event.fireEvent(Event.java:198)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at javafx.scene.control.MenuItem.fire(MenuItem.java:459)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1385)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1338)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at javafx.event.Event.fireEvent(Event.java:198)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at javafx.scene.Scene$MouseHandler.process(Scene.java:3890)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at javafx.scene.Scene.processMouseEvent(Scene.java:1885)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2618)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at java.security.AccessController.doPrivileged(AccessController.java:101)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.glass.ui.View.notifyMouse(View.java:942)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Lcom_sun_glass_ui_View_2_0002enotifyMouse_00028IIIIIIIZZ_00029V(JNIJavaCallWrappers.java:0)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at java.lang.Thread.run(Thread.java:834)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] Caused by: org.apache.commons.logging.LogConfigurationException: No suitable Log implementation
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at org.apache.commons.logging.impl.LogFactoryImpl.discoverLogImplementation(LogFactoryImpl.java:848)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at org.apache.commons.logging.impl.LogFactoryImpl.newInstance(LogFactoryImpl.java:541)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:292)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:269)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:655)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at org.apache.http.conn.ssl.AbstractVerifier.<init>(AbstractVerifier.java:60)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at org.apache.http.conn.ssl.AllowAllHostnameVerifier.<init>(AllowAllHostnameVerifier.java:43)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at org.apache.http.conn.ssl.AllowAllHostnameVerifier.<clinit>(AllowAllHostnameVerifier.java:45)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:351)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:271)
[вт авг. 04 22:32:01 MSK 2020][FINE] [SUB] 	... 55 more
[вт авг. 04 22:32:03 MSK 2020][FINE] Result for run until end: 0
```

**Comment by EvokeAngle** [comment]
I am using org.slf4j:slf4j-api library,  something added:
`<list>org.slf4j.impl.StaticMarkerBinder</list>`
but something Appeared:
`Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: org.slf4j.impl.StaticMarkerBinder.getSingleton(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.`

**Comment by Shadow326159** [comment]
I solved this problem of mine. In addition to the classes in the reflectionList, you need to add:
`-H: ReflectionConfigurationFiles = $ {project.basedir} /reflection-config.json`
As a result, the configuration will look like:
```
                <configuration>
                    <reflectionList>
                        <list> org.dman.Controller </list>
                        <list> javafx.scene.control.SplitMenuButton </list>
                        <list> javafx.scene.control.MenuButton </list>
                        <list> javafx.scene.control.MenuItem </list>
                        <list> org.apache.commons.logging.LogFactory </list>
                        <list> org.apache.commons.logging.impl.LogFactoryImpl </list>
                    </reflectionList>
                    <nativeImageArgs>
                        <nativeImageArg>
                            -H: ReflectionConfigurationFiles = $ {project.basedir} /reflection-config.json
                        </nativeImageArg>
                    </nativeImageArgs>
                    <mainClass> $ {mainClassName} </mainClass>
                </configuration>
```
and the reflection-config.json file
```

[
  {
    "name": "org.apache.commons.logging.impl.SimpleLog",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredClasses": true,
    "allPublicClasses": true
  }
]
```

**Comment by jperedadnr** [comment]
Why didn't you add `org.apache.commons.logging.impl.SimpleLog` directly to the `reflectionList`? It will do exactly the same (adding the same content to the reflection json file). See https://docs.gluonhq.com/client/#_reflectionlist

**Comment by Shadow326159** [comment]
> Why didn't you add `org.apache.commons.logging.impl.SimpleLog` directly to the `reflectionList`? It will do exactly the same (adding the same content to the reflection json file). See https://docs.gluonhq.com/client/#_reflectionlist

Didn't think well. thank :)
