### ISSUE TITLE
UnsatisfiedLinkError: dlopen failed: cannot locate symbol "JVM_LatestUserDefinedLoader"

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/substrate#756]
Follow-up of https://github.com/gluonhq/client-maven-plugin/issues/246

The symbol is referred to by `libjava.a` for Android: 
```
$ cd ~/.gluon/substrate/javaStaticSdk/11-ea+1/android-aarch64/labs-staticjdk/lib/static
$ nm libjava.a | grep -i latest
0000000000000000 T Java_jdk_internal_misc_VM_latestUserDefinedLoader0
                 U JVM_LatestUserDefinedLoader
```

**Comment by jperedadnr** [comment]
This HelloWorld class reproduces the issue:

```
package hello;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.ObjectStreamClass;

public class HelloWorld {

    private static class ObjectInputStreamDemo extends ObjectInputStream {

        public ObjectInputStreamDemo(InputStream in) throws IOException {
            super(in);
        }

        public void resolve() throws IOException, ClassNotFoundException {
            // read and print an object and cast it as string
            System.out.println("" + (String) readUTF());

            // get the class for string and print the name
            ObjectStreamClass streamClass = ObjectStreamClass.lookup(Integer.class);
            System.out.println("" + resolveClass(streamClass).getName());
        }
    }

    public static void main(String[] args) {
        System.out.println("Hello World!!");

        String s = "Hello World";

        try {
            // create a new file with an ObjectOutputStream
            FileOutputStream out = new FileOutputStream("test.txt");
            ObjectOutputStream oout = new ObjectOutputStream(out);

            // write something in the file
            oout.writeUTF(s);
            oout.flush();

            // create an ObjectInputStream for the file we created before
            ObjectInputStreamDemo ois = new ObjectInputStreamDemo(new FileInputStream("test.txt"));
            ois.resolve();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        System.exit(0);
    }

}
```

with output:

```
==================== RUN TASK ====================
[SUB] --------- beginning of main
[SUB] --------- beginning of system
[SUB] V/GraalActivity( 5230): onCreate start, using Android Logging v1
[SUB] V/GraalActivity( 5230): onCreate done
[SUB] V/GraalActivity( 5230): onStart
[SUB] V/GraalActivity( 5230): onStart done
[SUB] V/GraalActivity( 5230): onResume
[SUB] V/GraalActivity( 5230): onResume done
[SUB] V/GraalActivity( 5230): surfaceCreated for com.gluonhq.helloandroid.MainActivity@2baa7b5
[SUB] V/GraalActivity( 5230): loading substrate library
[SUB] --------- beginning of crash
[SUB] E/AndroidRuntime( 5230): FATAL EXCEPTION: main
[SUB] E/AndroidRuntime( 5230): Process: hello.helloworld, PID: 5230
[SUB] E/AndroidRuntime( 5230): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "JVM_LatestUserDefinedLoader" referenced by "/data/app/hello.helloworld-v5KyaXcwYAXbHRYQyM-A5Q==/lib/arm64/libsubstrate.so"...
[SUB] E/AndroidRuntime( 5230):  at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
[SUB] E/AndroidRuntime( 5230):  at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
[SUB] E/AndroidRuntime( 5230):  at java.lang.System.loadLibrary(System.java:1667)
[SUB] E/AndroidRuntime( 5230):  at com.gluonhq.helloandroid.MainActivity.surfaceCreated(MainActivity.java:104)
```

**Comment by DeanWookey** [comment]
We removed all usages of ObjectInputStream from our code, however we still hit the issue. 

It turns out even with a simple java project, if you generate your own reflectionconfig.json using "agentlib:native-image-agent=config-output-dir=native-conf" (https://www.graalvm.org/reference-manual/native-image/BuildConfiguration/), it pretty much always generates this:
```
{
  "name":"java.io.ObjectInputStream",
  "allPublicMethods":true
}
```
Manually removing that solved our issue and also allowed us to have usages of ObjectInputStream in our code as long as we don't invoke them. We found that some of our libraries also contained ObjectInputStream usages like the apache HTTP library, but they don't seem to be called at runtime. I think you have to have --report-unsupported-elements-at-runtime arg set on the native-image command in order to allow this?

```
                <configuration>
                    <verbose>true</verbose>
                    <target>android</target>
                    <mainClass>${mainClassName}</mainClass>
                    <nativeImageArgs>
                        <arg>-H:+AllowIncompleteClasspath</arg>
                        <arg>--report-unsupported-elements-at-runtime</arg>
                    </nativeImageArgs>
                </configuration>
```

**Comment by jperedadnr** [comment]
This issue should be fixed with the latest Substrate, GraalVM and cLibraries versions, that prevent the need of JVM_XXX symbols.
