### ISSUE TITLE
MySQL connection

### ISSUE THREAD

**Issue by DMan326159** [gluonhq/substrate#773]
I am using MySQL database in my application. When I try to connect to it, I get the following report:

```
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] Exception in thread "JavaFX Application Thread" java.lang.ClassCastException: com.mysql.cj.exceptions.CJException cannot be cast to com.mysql.cj.exceptions.WrongArgumentException
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.mysql.cj.util.Util.getInstance(Util.java:169)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.mysql.cj.util.Util.getInstance(Util.java:174)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.mysql.cj.conf.ConnectionUrl$Type.getImplementingInstance(ConnectionUrl.java:241)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.mysql.cj.conf.ConnectionUrl$Type.getConnectionUrlInstance(ConnectionUrl.java:211)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.mysql.cj.conf.ConnectionUrl.getConnectionUrlInstance(ConnectionUrl.java:280)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:194)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at java.sql.DriverManager.getConnection(DriverManager.java:677)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at java.sql.DriverManager.getConnection(DriverManager.java:228)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at org.dman.DatabaseHandler.getDbConnection(DatabaseHandler.java:14)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at org.dman.DatabaseHandler.getSurebets(DatabaseHandler.java:61)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at org.dman.JournalController.update(JournalController.java:567)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at org.dman.JournalController.lambda$initialize$9(JournalController.java:615)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at org.dman.JournalController.setWeek(JournalController.java:72)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at org.dman.JournalController.lambda$initialize$7(JournalController.java:610)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at javafx.event.Event.fireEvent(Event.java:198)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3597)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at javafx.scene.Scene$MouseHandler.process(Scene.java:3899)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at javafx.scene.Scene.processMouseEvent(Scene.java:1885)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2618)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at java.security.AccessController.doPrivileged(AccessController.java:101)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.sun.glass.ui.View.notifyMouse(View.java:942)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Lcom_sun_glass_ui_View_2_0002enotifyMouse_00028IIIIIIIZZ_00029V(JNIJavaCallWrappers.java:0)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at java.lang.Thread.run(Thread.java:834)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
[пн сент. 14 15:26:15 MSK 2020][FINE] [SUB] 	at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)
[пн сент. 14 15:26:17 MSK 2020][FINE] Result for run until end: 0
```

I found similar cases from other GraalVM users, but I did not find a specific solution. Is there any way to solve the problem?

**Comment by jperedadnr** [comment]
Closing as not enough details to reproduce. 
Feel free to reopen once you have tested the latest Substrate and GraalVM versions.
