### ISSUE TITLE
Compilation Fails when using an extension of java.util.zip.Inflater

### ISSUE THREAD

**Issue by LordTylus** [gluonhq/substrate#793]
Hello there,

currently I am evaluating Gluon as an alternative to RoboVM, The examples ran fine but I noticed some issues where GraalVM throws some compile errors when using the OkHttp Framework (I was using a pretty old version of that, not sure if a current version has the same issues). 

I narrowed it down to an anonymous implementation of the java.util.zip.Inflater inside the Framework and was able to Reproduce it with a Modified Version of the HelloFXML sample.

Basically I just added a Nested Inflater implementation and create an instance of it. I am not entirely sure what causes it to fail and if it is an actual GraalVM issue, or maybe something triggered by Gluon itself. 

For my evaluation I could workaround it by removing  the non needed code in the OkHttp Framework as it was only needed for the Client to support Spdy/3 which I dont need. But I thought I would let you know about my findings. 

For my Test I used
graalvm-ce-java11-darwin-amd64-20.2.0
GluonClientPlugin Version 0.1.32 (not sure which version of substrate it uses) 

And I am trying to Build the iOS Profile

```
public class HelloFXML extends Application {

    private final class NewInflater extends Inflater {
        @Override
        public int inflate(byte[] buffer, int offset, int count)
                throws DataFormatException {
            int result = super.inflate(buffer, offset, count);

            return result;
        }
    }

    @Override
    public void start(Stage stage) throws IOException {

        NewInflater newInflater = new NewInflater();

        AnchorPane root = FXMLLoader.load(HelloFXML.class.getResource("hello.fxml"),
                ResourceBundle.getBundle("hellofx.hello"));
        Scene scene = new Scene(root, 640, 480);
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
```

```
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] Error: Incompatible change of initialization policy for java.util.zip.Inflater: trying to change RERUN for JDK native code support via JNI to BUILD_TIME super type of hellofx.HelloFXML$NewInflater
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] com.oracle.svm.core.util.UserError$UserException: Incompatible change of initialization policy for java.util.zip.Inflater: trying to change RERUN for JDK native code support via JNI to BUILD_TIME super type of hellofx.HelloFXML$NewInflater
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:99)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insert(ClassInitializationConfiguration.java:64)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.forceInitializeHosted(ConfigurableClassInitialization.java:472)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.forceInitializeHosted(ConfigurableClassInitialization.java:476)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.lambda$initializeSafeDelayedClasses$11(ClassInitializationFeature.java:319)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.initializeSafeDelayedClasses(ClassInitializationFeature.java:316)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.afterAnalysis(ClassInitializationFeature.java:256)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:753)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:753)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:555)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:468)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[Mi. Sep. 23 13:41:43 MESZ 2020][INFO] [SUB] Error: Image build request failed with exit status 1
```

**Comment by mipastgt** [comment]
This seems to be a critical bug because it happens quite often in different constellations. I had the same problem and reported it to Oracle here: https://github.com/oracle/graal/issues/2901
It is a GraalVM/native-image issue and not a Gluon substrate issue.

**Comment by jperedadnr** [comment]
GraalVM issue has been fixed
