### ISSUE TITLE
Android: NPE at MonocleWindowManager when launching the app

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/substrate#810]
The issue happens after #809 integration (bumping JavaFX static version). 

It is not critical (HelloGluon still works fine), but the window might not be properly laid out in case of HelloFX).

```
[SUB] V/GraalActivity(26378): surfaceredraw needed (and wait) done
[SUB] D/GraalCompiled(26378): Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
[SUB] D/GraalCompiled(26378):     at com.sun.glass.ui.monocle.MonocleWindowManager$1.run(MonocleWindowManager.java:179)
[SUB] D/GraalCompiled(26378):     at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
[SUB] D/GraalCompiled(26378):     at java.security.AccessController.doPrivileged(AccessController.java:101)
[SUB] D/GraalCompiled(26378):     at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
[SUB] D/GraalCompiled(26378):     at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)
[SUB] D/GraalCompiled(26378):     at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
[SUB] D/GraalCompiled(26378):     at java.lang.Thread.run(Thread.java:834)
[SUB] D/GraalCompiled(26378):     at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
[SUB] D/GraalCompiled(26378):     at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
```

The issue is related to this PR in OpenJFX: https://github.com/openjdk/jfx/pull/153, and this [commit](https://github.com/openjdk/jfx/pull/153/files#diff-7577ded02642f1986ffb22a6a888e95aR124) that prevents setting `focusedWindow` if `window` is not visible yet:

```
boolean requestFocus(MonocleWindow window) {
        int index = getWindowIndex(window);
        if (index != -1 && window.isVisible()) {
            focusedWindow = window;
            window.notifyFocus(WindowEvent.FOCUS_GAINED);
            return true;
        } else {
            return false;
        }
    }
```

causing the NPE in `repaintFromNative`:

```
MonocleWindow getFocusedWindow() {
        return focusedWindow;
}

static void repaintFromNative () {
        Platform.runLater(new Runnable () {

            @Override
            public void run() {
                Screen.notifySettingsChanged();
                instance.getFocusedWindow().setFullScreen(true); // <--- NPE
                instance.repaintAll();
                Toolkit.getToolkit().requestNextPulse();
            }
        });
    }
``

**Comment by jperedadnr** [comment]
See https://bugs.openjdk.java.net/browse/JDK-8254605
