### ISSUE TITLE
Problem running on Pixel 5 / Android 11

### ISSUE THREAD

**Issue by taranion** [gluonhq/substrate#840]
I have created an APK with the client-maven-plugin and the app runs perfectly on my old Android 8 device.
However on my new Pixel 5 with Android 11 it doesn't even start.

Here is the relevant block from the USB logging that shows an UnsatisfiedLinError for libsubstrate.so:
```
11-22 12:16:05.736 25325 25351 I AdrenoGLES-0: QUALCOMM build                   : 35605c3, Ia11ce2d146
11-22 12:16:05.736 25325 25351 I AdrenoGLES-0: Build Date                       : 09/02/20
11-22 12:16:05.736 25325 25351 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.31.04.00
11-22 12:16:05.736 25325 25351 I AdrenoGLES-0: Local Branch                     : gfx-adreno.lnx.2.0
11-22 12:16:05.736 25325 25351 I AdrenoGLES-0: Remote Branch                    : 
11-22 12:16:05.736 25325 25351 I AdrenoGLES-0: Remote Branch                    : 
11-22 12:16:05.736 25325 25351 I AdrenoGLES-0: Reconstruct Branch               : 
11-22 12:16:05.736 25325 25351 I AdrenoGLES-0: Build Config                     : S P 10.0.4 AArch64
11-22 12:16:05.736 25325 25351 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
11-22 12:16:05.738 25325 25325 V GraalActivity: surfaceCreated for com.gluonhq.helloandroid.MainActivity@c81e601
11-22 12:16:05.738 25325 25325 V GraalActivity: loading substrate library
11-22 12:16:05.771 25325 25325 D AndroidRuntime: Shutting down VM
11-22 12:16:05.772 25325 25325 E AndroidRuntime: FATAL EXCEPTION: main
11-22 12:16:05.772 25325 25325 E AndroidRuntime: Process: de.rpgframework.splittermond.mondtor, PID: 25325
11-22 12:16:05.772 25325 25325 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZdaPv" referenced by "/data/app/~~ldg4MGwcu79H52ZEqGiwNg==/de.rpgframework.splittermond.mondtor-l4yK4VsxUEpjw60lKop40g==/lib/arm64/libsubstrate.so"...
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1664)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at com.gluonhq.helloandroid.MainActivity.surfaceCreated(MainActivity.java:104)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at android.view.SurfaceView.updateSurface(SurfaceView.java:1153)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at android.view.SurfaceView.lambda$new$0$SurfaceView(SurfaceView.java:173)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at android.view.-$$Lambda$SurfaceView$w68OV7dB_zKVNsA-r0IrAUtyWas.onPreDraw(Unknown Source:2)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1093)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3074)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1946)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8156)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:731)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
11-22 12:16:05.773 25325 25351 I AdrenoGLES-0: PFP: 0x016dd090, ME: 0x00000000
11-22 12:16:05.776 25325 25351 E Adreno-AppProfiles: Could not find QSPM HAL service
11-22 12:16:05.776  1635 25355 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
11-22 12:16:05.776  1635  6609 W ActivityTaskManager:   Force finishing activity de.rpgframework.splittermond.mondtor/com.gluonhq.helloandroid.MainActivity
11-22 12:16:05.781 25325 25351 W AdrenoUtils: <ReadGpuID_from_sysfs:197>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
11-22 12:16:05.781 25325 25351 W AdrenoUtils: <ReadGpuID:221>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
```

**Comment by jperedadnr** [comment]
@taranion @makingthematrix We are investigating the issue.
So far, we have bumped Android platform and build tools from 29 (Android 10) to 30 (Android 11).
We don't have a device to test, so it would be great if you could test these apps and report back:

- [App 1](https://drive.google.com/file/d/1k5Q9nGby8kdldrXDQjbJOlqvpcApl-7b/view?usp=sharing)
- [App 2](https://drive.google.com/file/d/1SzL4Ibuz9Qinz0g8tAVBMH6VKq5Gd6el/view?usp=sharing)

Both are the same app, but with some internal differences.

**Comment by makingthematrix** [comment]
@jperedadnr 
Both fail. Here are the logs:
[DoodleTrace.log](https://github.com/gluonhq/substrate/files/5852068/DoodleTrace.log)
[app-debug.log](https://github.com/gluonhq/substrate/files/5852069/app-debug.log)

**Comment by jperedadnr** [comment]
@makingthematrix Thanks for testing. I've just uploaded a new version of [`app-debug.apk`](https://drive.google.com/file/d/1EkG-LX_2V4y7Vd3ti6kC_R171vdSECXr/view?usp=sharing). Can you please test again?

**Comment by makingthematrix** [comment]
@jperedadnr : Works! :)
[app-debug2.log](https://github.com/gluonhq/substrate/files/5852223/app-debug2.log)

**Comment by jperedadnr** [comment]
Cool! Great news

**Comment by taranion** [comment]
I cannot debug at the moment, but I was able to test the APKs
"App 1" failed
"App 2" and app-debug.apk run perfectly

**Comment by jperedadnr** [comment]
Thanks for testing, at least we are on the right track now.

**Comment by taranion** [comment]
App 1 produced the same problem
```01-21 22:46:03.677   718   718 E AndroidRuntime: FATAL EXCEPTION: main
01-21 22:46:03.677   718   718 E AndroidRuntime: Process: com.gluonhq.samples.doodletrace, PID: 718
01-21 22:46:03.677   718   718 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZdaPv" referenced by "/data/app/~~zKKMLhxzUv_sKEMZlUmsvw==/com.gluonhq.samples.doodletrace-XhQ8QCbqE14L-So3PWolGg==/lib/arm64/libsubstrate.so"...
01-21 22:46:03.677   718   718 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
01-21 22:46:03.677   718   718 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
01-21 22:46:03.677   718   718 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1664)
01-21 22:46:03.677   718   718 E AndroidRuntime: 	at com.gluonhq.helloandroid.MainActivity.surfaceCreated(MainActivity.java:104)
```

But great news, that you found the source of this. Congratulations.

**Comment by jperedadnr** [comment]
@makingthematrix @taranion I've uploaded [app-debug3.apk](https://drive.google.com/file/d/1yEQoXL2USF1HLvJeFGxZ4PGeFZvnZUNr/view?usp=sharing), hopefully a slightly improved version. Could you test and report back? Thx!

**Comment by taranion** [comment]
Still working
```
01-22 11:36:29.258  1543  1711 D EventSequenceValidator: inc AccIntentStartedEvents to 2
01-22 11:36:29.258  1543  5080 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.gluonhq.samples.doodletrace/com.gluonhq.helloandroid.MainActivity bnds=[37,1323][238,1634]} from uid 10244
01-22 11:36:29.271   959  1066 I CHRE    : @ 62134.010: [ip] Peak detected: magnitude = 0.140480 hpa, duration = 40.000000 ms
01-22 11:36:29.271   959  2004 I sensors-hal: onBaroPeakMessage:81, Barometric peak detected: magnitude = 0.140480 hPa (bucket: 3), duration = 40.000000 ms (bucket: 3).
01-22 11:36:29.271   938  1682 I CapoDetector: handleNanoappMessage, Id 5147455389092024354, type 3, size 8
01-22 11:36:29.271  1543  2286 E ContextHubClientManager: Cannot send message to unregistered client (host endpoint ID = -28638)
01-22 11:36:29.272  1543  1711 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 10317; state: DISABLED
01-22 11:36:29.273  1543  1711 D CompatibilityChangeReporter: Compat change id reported: 135754954; UID 10317; state: ENABLED
01-22 11:36:29.273  1543  1740 D CompatibilityChangeReporter: Compat change id reported: 143937733; UID 10317; state: ENABLED
01-22 11:36:29.273   959  2004 I sensors-hal: reportVendorAtom:28, Vendor atom [id = 100047] reported.
01-22 11:36:29.286   926   926 D Zygote  : Forked child process 26429
01-22 11:36:29.291  1543  1740 I ActivityManager: Start proc 26429:com.gluonhq.samples.doodletrace/u0a317 for pre-top-activity {com.gluonhq.samples.doodletrace/com.gluonhq.helloandroid.MainActivity}
01-22 11:36:29.294 26429 26429 I les.doodletrac: Late-enabling -Xcheck:jni
01-22 11:36:29.307 26429 26429 I les.doodletrac: Unquickening 12 vdex files!
01-22 11:36:29.311 31506 31511 I adbd    : jdwp connection from 26429
01-22 11:36:29.336 26429 26429 W ActivityThread: Application com.gluonhq.samples.doodletrace can be debugged on port 8100...
01-22 11:36:29.365 26429 26429 D NetworkSecurityConfig: No Network Security Config specified, using platform default
01-22 11:36:29.366 26429 26429 D NetworkSecurityConfig: No Network Security Config specified, using platform default
01-22 11:36:29.370   582   602 W DisplayIdentification: Invalid EDID: falling back to serial number due to missing display name.
01-22 11:36:29.370   582   602 W DisplayIdentification: Invalid EDID: falling back to ASCII text due to missing serial number.
01-22 11:36:29.378 26429 26429 V GraalActivity: onCreate start, using Android Logging v1
01-22 11:36:29.378 26429 26429 W System.err: onCreate called, writing this to System.err
01-22 11:36:29.388 26429 26429 V GraalActivity: onCreate done
01-22 11:36:29.390 26429 26429 V GraalActivity: onStart
01-22 11:36:29.390 26429 26429 V GraalActivity: onStart done
01-22 11:36:29.390 26429 26429 V GraalActivity: onResume
01-22 11:36:29.390 26429 26429 V GraalActivity: onResume done
01-22 11:36:29.409 26429 26451 I AdrenoGLES-0: QUALCOMM build                   : 35605c3, Ia11ce2d146
01-22 11:36:29.409 26429 26451 I AdrenoGLES-0: Build Date                       : 09/02/20
01-22 11:36:29.409 26429 26451 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.31.04.00
01-22 11:36:29.409 26429 26451 I AdrenoGLES-0: Local Branch                     : gfx-adreno.lnx.2.0
01-22 11:36:29.409 26429 26451 I AdrenoGLES-0: Remote Branch                    : 
01-22 11:36:29.409 26429 26451 I AdrenoGLES-0: Remote Branch                    : 
01-22 11:36:29.409 26429 26451 I AdrenoGLES-0: Reconstruct Branch               : 
01-22 11:36:29.409 26429 26451 I AdrenoGLES-0: Build Config                     : S P 10.0.4 AArch64
01-22 11:36:29.409 26429 26451 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
01-22 11:36:29.411 26429 26429 V GraalActivity: surfaceCreated for com.gluonhq.helloandroid.MainActivity@111d7ca
01-22 11:36:29.411 26429 26429 V GraalActivity: loading substrate library
01-22 11:36:29.413 26429 26451 I AdrenoGLES-0: PFP: 0x016dd090, ME: 0x00000000
01-22 11:36:29.432 26429 26429 E GraalGluon: AndroidVM called JNI_OnLoad, vm = 0xb40000734c2e5f10, androidEnv = 0xb40000733c2d6c70
01-22 11:36:29.432 26429 26429 V GraalActivity: loaded substrate library
01-22 11:36:29.432 26429 26429 E GraalGluon: nativeSetSurface called, env at 0xb40000733c2d6c70 and size 8, surface at 0x7fc4d70728
01-22 11:36:29.432 26429 26429 I GLASS   : initialize from native can't be done without JVM
01-22 11:36:29.432 26429 26429 I GLASS   : after androidSetNativeWindow asked, window is 0xb4000073fc2ee6d0
01-22 11:36:29.432 26429 26429 E GraalGluon: native setSurface Ready, native window at 0xb4000073fc2ee6d0
01-22 11:36:29.433 26429 26429 V GraalActivity: metrics = DisplayMetrics{density=2.75, width=1080, height=2072, scaledDensity=2.75, xdpi=435.428, ydpi=433.839}, density = 2.75
01-22 11:36:29.433 26429 26429 E GraalGluon: SurfaceReady, surface at 0x7fc4d70708
01-22 11:36:29.433 26429 26429 I GLASS   : initialize from native can't be done without JVM
01-22 11:36:29.433 26429 26429 I GLASS   : after androidSetNativeWindow asked, window is 0xb4000073fc2ee6d0
01-22 11:36:29.433 26429 26429 I GLASS   : initialize from native can't be done without JVM
01-22 11:36:29.433 26429 26429 E GraalGluon: SurfaceReady, native window at 0xb4000073fc2ee6d0
01-22 11:36:29.433 26429 26429 V GraalActivity: Surface created, native code informed about it, nativeWindow at -5476376648730351920
01-22 11:36:29.433 26429 26429 V GraalActivity: We will now launch Graal in a separate thread
01-22 11:36:29.434 26429 26429 V GraalActivity: graalStarted true
01-22 11:36:29.434 26429 26429 V GraalActivity: surfaceCreated done
01-22 11:36:29.434 26429 26429 V GraalActivity: surfaceChanged start
01-22 11:36:29.434 26429 26429 V GraalActivity: [MainActivity] surfaceChanged, format = 4, width = 1080, height = 2063
01-22 11:36:29.434 26429 26429 E GraalGluon: nativeSetSurface called, env at 0xb40000733c2d6c70 and size 8, surface at 0x7fc4d70738
01-22 11:36:29.434 26429 26455 E GraalGluon: Start GraalApp, DALVIK env at 0xb40000733c2df5f0
01-22 11:36:29.434 26429 26429 I GLASS   : initialize from native can't be done without JVM
01-22 11:36:29.434 26429 26455 E GraalGluon: PAGESIZE = 4096
01-22 11:36:29.434 26429 26455 E GraalGluon: EnvVersion = 65542
01-22 11:36:29.434 26429 26429 I GLASS   : after androidSetNativeWindow asked, window is 0xb4000073fc2ee6d0
01-22 11:36:29.434 26429 26429 E GraalGluon: native setSurface Ready, native window at 0xb4000073fc2ee6d0
01-22 11:36:29.434 26429 26455 E GraalGluon: calling JavaMainWrapper_run with argsize: 21
01-22 11:36:29.434 26429 26429 V GraalActivity: surfaceChanged done, metrics = DisplayMetrics{density=2.75, width=1080, height=2072, scaledDensity=2.75, xdpi=435.428, ydpi=433.839}, density = 2.75
01-22 11:36:29.434 26429 26429 V GraalActivity: SurfaceRedraw needed start
01-22 11:36:29.434 26429 26429 V GraalActivity: ask native graallayer to redraw surface
01-22 11:36:29.434 26429 26429 E GraalGluon: launcher, nativeSurfaceRedrawNeeded called. Invoke method on glass_monocle
01-22 11:36:29.434 26429 26429 I GLASS   : Native code is notified that surface needs to be redrawn (repaintall)
01-22 11:36:29.434 26429 26429 I GLASS   : we can't do this yet, no jVM
01-22 11:36:29.434 26429 26455 E GraalGluon: determineCpuFeaures
01-22 11:36:29.433 26429 26429 W Thread-2: type=1400 audit(0.0:3446): avc: denied { read } for name="if_inet6" dev="proc" ino=4026532077 scontext=u:r:untrusted_app:s0:c61,c257,c512,c768 tcontext=u:object_r:proc_net:s0 tclass=file permissive=0 app=com.gluonhq.samples.doodletrace
01-22 11:36:29.436 26429 26451 W AdrenoUtils: <ReadGpuID_from_sysfs:197>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
01-22 11:36:29.436 26429 26451 W AdrenoUtils: <ReadGpuID:221>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
01-22 11:36:29.436 26429 26454 D GraalCompiled: Prism pipeline init order: es2 
01-22 11:36:29.436 26429 26454 D GraalCompiled: Using Double Precision Marlin Rasterizer
01-22 11:36:29.436 26429 26454 D GraalCompiled: Using dirty region optimizations
01-22 11:36:29.436 26429 26454 D GraalCompiled: Using system sized mask for primitives
01-22 11:36:29.436 26429 26454 D GraalCompiled: Not forcing power of 2 sizes for textures
01-22 11:36:29.436 26429 26454 D GraalCompiled: Using hardware CLAMP_TO_ZERO mode
01-22 11:36:29.436 26429 26454 D GraalCompiled: Opting in for HiDPI pixel scaling
01-22 11:36:29.437 26429 26454 D GraalCompiled: Prism pipeline name = com.sun.prism.es2.ES2Pipeline
01-22 11:36:29.437 26429 26454 D GraalCompiled: Loading ES2 native library ... prism_es2_monocle
01-22 11:36:29.437 26429 26454 D GraalCompiled: WARNING: java.lang.UnsatisfiedLinkError
01-22 11:36:29.437 26429 26457 E javafx  : In JNI_OnLoad_prism_es2
01-22 11:36:29.437 26429 26454 D GraalCompiled: System.loadLibrary(prism_es2_monocle) succeeded
01-22 11:36:29.437 26429 26454 D GraalCompiled: 	succeeded.
01-22 11:36:29.437 26429 26454 D GraalCompiled: GLFactory using com.sun.prism.es2.MonocleGLFactory
01-22 11:36:29.438 26429 26454 D GraalCompiled: WARNING: java.lang.UnsatisfiedLinkError
01-22 11:36:29.438 26429 26454 D GraalCompiled: In JNI_OnLoad_glass)monocle
01-22 11:36:29.438 26429 26454 D GraalCompiled: System.loadLibrary(glass_monocle) succeeded
01-22 11:36:29.433 26429 26429 W Thread-2: type=1400 audit(0.0:3447): avc: denied { read } for name="ipv6_route" dev="proc" ino=4026532078 scontext=u:r:untrusted_app:s0:c61,c257,c512,c768 tcontext=u:object_r:proc_net:s0 tclass=file permissive=0 app=com.gluonhq.samples.doodletrace
01-22 11:36:29.438 26429 26457 I GLASS   : I have to Call dlopen libGLESv2.so
01-22 11:36:29.438 26429 26457 I GLASS   : handle = 0x498ef89969c9c957
01-22 11:36:29.438 26429 26457 I GLASS   : I have to Call dlopen libEGL.so
01-22 11:36:29.439 26429 26457 I GLASS   : handle = 0x59d1405ba2431831
01-22 11:36:29.439 26429 26457 I GLASS   : Initializing native Android Bridge from Java code
01-22 11:36:29.439 26429 26457 I GLASS   : Initializing native Android Bridge done
01-22 11:36:29.433 26429 26429 W Thread-2: type=1400 audit(0.0:3448): avc: denied { read } for name="if_inet6" dev="proc" ino=4026532077 scontext=u:r:untrusted_app:s0:c61,c257,c512,c768 tcontext=u:object_r:proc_net:s0 tclass=file permissive=0 app=com.gluonhq.samples.doodletrace
01-22 11:36:29.433 26429 26429 W Thread-2: type=1400 audit(0.0:3449): avc: denied { read } for name="cgroups" dev="proc" ino=4026531855 scontext=u:r:untrusted_app:s0:c61,c257,c512,c768 tcontext=u:object_r:proc:s0 tclass=file permissive=0 app=com.gluonhq.samples.doodletrace
01-22 11:36:29.441 26429 26454 D GraalCompiled: (X) Got class = class com.sun.prism.es2.ES2Pipeline
01-22 11:36:29.441 26429 26454 D GraalCompiled: Initialized prism pipeline: com.sun.prism.es2.ES2Pipeline
01-22 11:36:29.441 26429 26454 D GraalCompiled: JavaFX: using com.sun.javafx.tk.quantum.QuantumToolkit
01-22 11:36:29.443 26429 26454 D GraalCompiled: Maximum supported texture size: 16384
01-22 11:36:29.443 26429 26454 D GraalCompiled: Maximum texture size clamped to 4096
01-22 11:36:29.443 26429 26454 D GraalCompiled: Non power of two texture support = true
01-22 11:36:29.443 26429 26454 D GraalCompiled: Maximum number of vertex attributes = 32
01-22 11:36:29.443 26429 26454 D GraalCompiled: Maximum number of uniform vertex components = 1024
01-22 11:36:29.443 26429 26454 D GraalCompiled: Maximum number of uniform fragment components = 1024
01-22 11:36:29.443 26429 26454 D GraalCompiled: Maximum number of varying components = 124
01-22 11:36:29.443 26429 26454 D GraalCompiled: Maximum number of texture units usable in a vertex shader = 16
01-22 11:36:29.443 26429 26454 D GraalCompiled: Maximum number of texture units usable in a fragment shader = 16
01-22 11:36:29.443 26429 26454 D GraalCompiled: Graphics Vendor: Qualcomm
01-22 11:36:29.443 26429 26454 D GraalCompiled:        Renderer: Adreno (TM) 620
01-22 11:36:29.443 26429 26454 D GraalCompiled:         Version: OpenGL ES 3.2 V@0490.0 (GIT@35605c3, Ia11ce2d146, 1599101106) (Date:09/02/20)
01-22 11:36:29.443 26429 26454 D GraalCompiled:  vsync: true vpipe: true
01-22 11:36:29.444 26429 26454 D GraalCompiled: WARNING: java.lang.UnsatisfiedLinkError
01-22 11:36:29.444 26429 26458 E GraalGluon: In dummy JNI_OnLoad_javafx_font
01-22 11:36:29.444 26429 26454 D GraalCompiled: System.loadLibrary(javafx_font) succeeded
01-22 11:36:29.503 26429 26458 D GluonAttach: Initializing native Util from OnLoad
01-22 11:36:29.503 26429 26458 D GluonAttach: Init Util
01-22 11:36:29.503 26429 26458 D GraalGluon: ATTACH_DALVIK, tid = 26458, existed? 0, dalvikEnv at 0xb40000733c33f470
01-22 11:36:29.503 26429 26458 D GluonAttach: Util :: Load className com/gluonhq/helloandroid/Util
01-22 11:36:29.503 26429 26458 D GraalGluon: ATTACH_DALVIK, tid = 26458, existed? 1, dalvikEnv at 0xb40000733c33f470
01-22 11:36:29.504 26429 26458 V GluonAttach: Util <init>
01-22 11:36:29.504 26429 26458 D GraalGluon: DETACH_DALVIK, tid = 26458, existed = 1, env at 0xb40000733c33f470
01-22 11:36:29.504 26429 26458 D GluonAttach: Dalvik Util init was called
01-22 11:36:29.504 26429 26458 I GluonAttach: JNI_OnLoad_display called
01-22 11:36:29.504 26429 26458 D GluonAttach: [Display Service] Initializing native Display from OnLoad
01-22 11:36:29.504 26429 26458 D GraalGluon: ATTACH_DALVIK, tid = 26458, existed? 1, dalvikEnv at 0xb40000733c33f470
01-22 11:36:29.504 26429 26458 D GraalGluon: ATTACH_DALVIK, tid = 26458, existed? 1, dalvikEnv at 0xb40000733c33f470
01-22 11:36:29.504 26429 26458 D GluonAttach: Util :: Load className com/gluonhq/helloandroid/DalvikDisplayService
01-22 11:36:29.504 26429 26458 D GraalGluon: DETACH_DALVIK, tid = 26458, existed = 1, env at 0xb40000733c33f470
01-22 11:36:29.505 26429 26454 D GraalCompiled: WARNING: java.lang.UnsatisfiedLinkError
01-22 11:36:29.505 26429 26454 D GraalCompiled: System.loadLibrary(javafx_font_freetype) succeeded
01-22 11:36:29.505 26429 26458 D GraalGluon: ATTACH_DALVIK, tid = 26458, existed? 1, dalvikEnv at 0xb40000733c33f470
01-22 11:36:29.505 26429 26458 D GraalGluon: DETACH_DALVIK, tid = 26458, existed = 1, env at 0xb40000733c33f470
01-22 11:36:29.525 26429 26458 I GluonAttach: JNI_OnLoad_storage called
01-22 11:36:29.525 26429 26458 D GluonAttach: [Storage Service] Initializing native Storage from OnLoad
01-22 11:36:29.525 26429 26458 D GraalGluon: ATTACH_DALVIK, tid = 26458, existed? 1, dalvikEnv at 0xb40000733c33f470
01-22 11:36:29.525 26429 26458 D GraalGluon: ATTACH_DALVIK, tid = 26458, existed? 1, dalvikEnv at 0xb40000733c33f470
01-22 11:36:29.525 26429 26458 D GluonAttach: Util :: Load className com/gluonhq/helloandroid/DalvikStorageService
01-22 11:36:29.525 26429 26458 D GraalGluon: DETACH_DALVIK, tid = 26458, existed = 1, env at 0xb40000733c33f470
01-22 11:36:29.530 26429 26454 D GraalCompiled: File not found: /system/etc/system_fonts.xml
01-22 11:36:29.622 26429 26458 D GraalGluon: ATTACH_DALVIK, tid = 26458, existed? 1, dalvikEnv at 0xb40000733c33f470
01-22 11:36:29.622 26429 26458 D GraalGluon: DETACH_DALVIK, tid = 26458, existed = 1, env at 0xb40000733c33f470
01-22 11:36:29.639 26429 26454 D GraalCompiled: max rectangle texture cell size = 89
01-22 11:36:29.650 26429 26454 D GraalCompiled: wrap rectangle texture = 2 x 2
01-22 11:36:29.650 26429 26454 D GraalCompiled: ES2ResourceFactory: Prism - createStockShader: AlphaTexture_Color.frag
01-22 11:36:29.677  1543  2069 D ConnectivityService: NetReassign [no changes]
01-22 11:36:29.706  2816  3009 I NearbySharing: FastInitiation warming period has ended [CONTEXT service_id=194 ]
01-22 11:36:29.727 26429 26454 D GraalCompiled: ES2ResourceFactory: Prism - createStockShader: FillCircle_RadialGradient_PAD.frag
01-22 11:36:29.729 26429 26454 D GraalCompiled: ES2ResourceFactory: Prism - createStockShader: Texture_Color.frag
01-22 11:36:29.730 26429 26454 D GraalCompiled: ES2ResourceFactory: Prism - createStockShader: FillRoundRect_Color.frag
01-22 11:36:29.732 26429 26454 D GraalCompiled: PPSRenderer: scenario.effect - createShader: LinearConvolveShadow_28
01-22 11:36:29.734 26429 26454 D GraalCompiled: ES2ResourceFactory: Prism - createStockShader: Solid_TextureRGB.frag
01-22 11:36:29.735 26429 26454 D GraalCompiled: PPSRenderer: scenario.effect - createShader: LinearConvolveShadow_20
01-22 11:36:29.762 26429 26454 D GraalCompiled: PPSRenderer: scenario.effect - createShader: LinearConvolveShadow_64
01-22 11:36:29.764 26429 26458 D GraalGluon: ATTACH_DALVIK, tid = 26458, existed? 1, dalvikEnv at 0xb40000733c33f470
01-22 11:36:29.764 26429 26458 D GraalGluon: DETACH_DALVIK, tid = 26458, existed = 1, env at 0xb40000733c33f470
01-22 11:36:29.786  2407  2407 I WallpaperService: engine paused
01-22 11:36:29.790   959   959 I sensors-hal: [hal]activate_physical_sensor:238, android.sensor.gyroscope/41 en=0
01-22 11:36:29.804   959   959 D Diag_Lib: diag: Diag_LSM_DeInit done for pid: 959
01-22 11:36:29.805   582   582 E Layer   : [Surface(name=Task=2271)/@0xa0e48f4 - animation-leash#0] No local sync point found
```

**Comment by jperedadnr** [comment]
Great, thanks!

**Comment by makingthematrix** [comment]
app-debug3.log works on my device as well (Google Pixel 5, Android 11).

**Comment by jperedadnr** [comment]
Thanks! We have now a fix that we'll integrate soon.

**Comment by jperedadnr** [comment]
@makingthematrix @taranion the fix has been integrated. You can test it now with plugin 0.1.37-SNAPSHOT adding this to the pom:

```
<pluginRepositories>
        <pluginRepository>
            <id>snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </pluginRepository>
    </pluginRepositories>
    ```

**Comment by makingthematrix** [comment]
@jperedadnr : All good. I tested it on my example app based on "Fifty States" from Gluon Samples. It crashed before, and it works well now.
