### ISSUE TITLE
java.lang.UnsatisfiedLinkError on Android 11, Google Pixel 5

### ISSUE THREAD

**Issue by makingthematrix** [gluonhq/substrate#863]
### Expected Behavior
1. Use the HelloFX example: https://github.com/gluonhq/gluon-samples/tree/master/HelloFX
2. Build the Android apk.
3. Install the apk on Android 11, Google Pixel 5
4. Run the app from the phone.
5. I should see the hello screen.

### Current Behavior
The app crashes immediately on opening. 

### Steps to Reproduce
As above

### Your Environment
Linux Mint 20.0.1 Cinnamon
GraalVM 20.3.0 or GraalVM 21.0.0
Java 11
Tried to run the built apk on Android 11, Google Pixel 5.
The crash does not occur on any other of my phones: one with Android 9, another with Android 10. I guess this is Android 11 thing.

I'm attaching the logs from adb logcat:
[error.log](https://github.com/gluonhq/substrate/files/5848303/error.log)

Here's the part I think can be relevant:
```
01-21 10:21:31.464 13725 13725 V GraalActivity: surfaceCreated for com.gluonhq.helloandroid.MainActivity@1e4bb5c
01-21 10:21:31.464 13725 13725 V GraalActivity: loading substrate library
01-21 10:21:31.466 13725 13748 I AdrenoGLES-0: PFP: 0x016dd090, ME: 0x00000000
01-21 10:21:31.484 13725 13725 D AndroidRuntime: Shutting down VM
01-21 10:21:31.485 13725 13725 E AndroidRuntime: FATAL EXCEPTION: main
01-21 10:21:31.485 13725 13725 E AndroidRuntime: Process: com.gluonhq.samples.hellofx, PID: 13725
01-21 10:21:31.485 13725 13725 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZdaPv" referenced by "/data/app/~~7HT8PGWQMDyPCgrWrMGWfg==/com.gluonhq.samples.hellofx-SevcUux-uY0FDDf8tD3tVA==/lib/arm64/libsubstrate.so"...
01-21 10:21:31.485 13725 13725 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
01-21 10:21:31.485 13725 13725 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
01-21 10:21:31.485 13725 13725 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1664)
01-21 10:21:31.485 13725 13725 E AndroidRuntime: 	at com.gluonhq.helloandroid.MainActivity.surfaceCreated(MainActivity.java:104)
01-21 10:21:31.485 13725 13725 E AndroidRuntime: 	at android.view.SurfaceView.updateSurface(SurfaceView.java:1153)
01-21 10:21:31.485 13725 13725 E AndroidRuntime: 	at android.view.SurfaceView.lambda$new$0$SurfaceView(SurfaceView.java:173)
```

**Comment by jperedadnr** [comment]
Duplicated of #840
