### ISSUE TITLE
java.lang.NoSuchFieldException: Private

### ISSUE THREAD

**Issue by DMan326159** [gluonhq/substrate#892]
I would like to send messages to telegram from my application, but I am getting a very strange error. In this case, a message is sent to telegram, but after this the application throws an exception and does not work further.

```
[яЄ ьрЁ. 19 18:16:54 MSK 2021][INFO] ==================== RUN TASK ====================
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB] Exception in thread "JavaFX Application Thread" java.lang.AssertionError: AssertionError (GSON 2.8.6): java.lang.NoSuchFieldException: Private

[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.google.gson.Gson.fromJson(Gson.java:949)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.google.gson.Gson.fromJson(Gson.java:897)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.google.gson.Gson.fromJson(Gson.java:846)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.google.gson.Gson.fromJson(Gson.java:817)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.pengrad.telegrambot.impl.TelegramBotClient.send(TelegramBotClient.java:72)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.pengrad.telegrambot.TelegramBot.execute(TelegramBot.java:42)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at org.dman.Controller.lambda$initialize$0(Controller.java:37)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at javafx.event.Event.fireEvent(Event.java:198)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at javafx.scene.Node.fireEvent(Node.java:8889)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at javafx.scene.control.Button.fire(Button.java:203)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:208)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at javafx.event.Event.fireEvent(Event.java:198)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at javafx.scene.Scene$MouseHandler.process(Scene.java:3856)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at javafx.scene.Scene.processMouseEvent(Scene.java:1851)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2584)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at java.security.AccessController.doPrivileged(AccessController.java:102)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.glass.ui.View.notifyMouse(View.java:942)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Lcom_sun_glass_ui_View_2_0002enotifyMouse_00028IIIIIIIZZ_00029V(JNIJavaCallWr
appers.java:0)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at java.lang.Thread.run(Thread.java:834)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB] Caused by: java.lang.AssertionError: java.lang.NoSuchFieldException: Private
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:792)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.google.gson.internal.bind.TypeAdapters$30.create(TypeAdapters.java:818)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.google.gson.Gson.getAdapter(Gson.java:458)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.google.gson.Gson.getAdapter(Gson.java:458)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.google.gson.Gson.getAdapter(Gson.java:458)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.google.gson.Gson.getAdapter(Gson.java:458)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.google.gson.Gson.fromJson(Gson.java:931)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      ... 54 more
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB] Caused by: java.lang.NoSuchFieldException: Private
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at java.lang.Class.getField(DynamicHub.java:1078)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:781)
[яЄ ьрЁ. 19 18:16:56 MSK 2021][INFO] [SUB]      ... 69 more
```

Controller.java

```
package org.dman;

import com.pengrad.telegrambot.TelegramBot;
import com.pengrad.telegrambot.request.SendMessage;
import javafx.fxml.FXML;
import javafx.scene.control.*;

public class Controller {

    private static final String telegramChatId = "";
    private static final TelegramBot telegramBot = new TelegramBot("");

    @FXML
    Button testsW;

    @FXML
    void initialize() {
        testsW.setOnAction(actionEvent -> telegramBot.execute(new SendMessage(telegramChatId, "test")));
    }
}
```

pom.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.dman</groupId>
    <artifactId>Arbitrage</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>15.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>15.0.1</version>
        </dependency>
        <dependency>
            <groupId>com.github.pengrad</groupId>
            <artifactId>java-telegram-bot-api</artifactId>
            <version>5.1.0</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>11</source>
                    <target>11</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.5</version>
                <configuration>
                    <mainClass>org.dman.Main</mainClass>
                </configuration>
            </plugin>

            <plugin>
                <groupId>com.gluonhq</groupId>
                <artifactId>client-maven-plugin</artifactId>
                <version>0.1.38</version>
                <configuration>
                    <target>${client.target}</target>
                    <mainClass>org.dman.Main</mainClass>
                    <reflectionList>
                        <list>org.dman.Controller</list>
                        
                        <list>com.pengrad.telegrambot.TelegramBot</list>
                        <list>com.pengrad.telegrambot.impl.TelegramBotClient</list>
                        <list>com.pengrad.telegrambot.UpdatesListener</list>
                        <list>com.pengrad.telegrambot.request.SendMessage</list>
                        <list>com.pengrad.telegrambot.response.SendResponse</list>
                        <list>com.pengrad.telegrambot.model.Message</list>
                        <list>com.pengrad.telegrambot.model.User</list>
                        <list>com.pengrad.telegrambot.model.Chat</list>
                    </reflectionList>
                    <nativeImageArgs>
                        <nativeImageArg>--allow-incomplete-classpath</nativeImageArg>
                    </nativeImageArgs>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>desktop</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <client.target>host</client.target>
            </properties>
        </profile>
        <profile>
            <id>ios</id>
            <properties>
                <client.target>ios</client.target>
            </properties>
        </profile>
        <profile>
            <id>android</id>
            <properties>
                <client.target>android</client.target>
            </properties>
        </profile>
    </profiles>
</project>
```

**Comment by jperedadnr** [comment]
Have you tried `mvn client:runagent`? That will run the app on HotSpot and provide a set of config files for native image. Make sure you try all possible actions. Then run again `mvn client:build client:run` and see if this time works.

**Comment by DMan326159** [comment]
> Have you tried `mvn client:runagent`? That will run the app on HotSpot and provide a set of config files for native image. Make sure you try all possible actions. Then run again `mvn client:build client:run` and see if this time works.

It fixed everything. Thank you!
