### ISSUE TITLE
How to fix java.lang.NoSuchMethodError when at runtime this error happens at windows pc with native exe?

### ISSUE THREAD

**Issue by abidmaqbool** [gluonhq/substrate#934]
I have crate native exe using Client Maven Plugin with Graalvm e.g. `mvn client:build` & run it e.g. `mvn client:run`.

At run time, when jfeonix library is used, error happens and my new form e.g. Mdi not opens

```
C:\Users\MaqboolStudioPC\Documents\heroku\esales-analyst>mvn client:run
[WARNING]
[WARNING] Some problems were encountered while building the effective settings
[WARNING] Expected root element 'settings' but found 'proxy' (position: START_TAG seen ...<proxies> -->\r\n\t\t<proxy>... @4:10)  @ C:\Users\MaqboolStudioPC\.m2\settings.xml, line 4, column 10
[WARNING]
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------< com.maqboolsolutions:esalesanalyst >-----------------
[INFO] Building eSales Analyst 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- client-maven-plugin:0.1.39:run (default-cli) @ esalesanalyst ---
[Sun May 16 16:01:39 PKT 2021][INFO] ==================== RUN TASK ====================
[Sun May 16 16:01:48 PKT 2021][INFO] [SUB] May 16, 2021 4:01:48 PM com.gluonhq.attach.util.Platform <clinit>
[Sun May 16 16:01:48 PKT 2021][INFO] [SUB] INFO: javafx.platform is not defined. Desktop will be assumed by default.
[Sun May 16 16:01:48 PKT 2021][INFO] [SUB] May 16, 2021 4:01:48 PM com.sun.javafx.application.PlatformImpl startup
[Sun May 16 16:01:48 PKT 2021][INFO] [SUB] WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @381e9837'
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB] Exception in thread "JavaFX Application Thread" java.lang.NoSuchMethodError: com.sun.javafx.scene.NodeHelper.treeShowingProperty(javafx.scene.Node)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.jfoenix.skins.JFXProgressBarSkin.<init>(JFXProgressBarSkin.java:64)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.jfoenix.controls.JFXProgressBar.createDefaultSkin(JFXProgressBar.java:73)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at javafx.scene.control.Control.doProcessCSS(Control.java:897)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at javafx.scene.Parent.doProcessCSS(Parent.java:1400)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at javafx.scene.Parent.doProcessCSS(Parent.java:1400)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at javafx.scene.Parent.doProcessCSS(Parent.java:1400)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at javafx.scene.Parent.doProcessCSS(Parent.java:1400)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at javafx.scene.Node.processCSS(Node.java:9456)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at javafx.scene.Scene.doCSSPass(Scene.java:569)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at javafx.scene.Scene.preferredSize(Scene.java:1750)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at javafx.scene.Scene$2.preferredSize(Scene.java:393)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at javafx.stage.Window$12.invalidated(Window.java:1111)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at javafx.stage.Window.setShowing(Window.java:1187)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at javafx.stage.Window.show(Window.java:1202)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at javafx.stage.Stage.show(Stage.java:273)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.maqboolsolutions.esalesanalyst.helper.view.View.createMdi(View.java:181)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.maqboolsolutions.esalesanalyst.module.login.Login.lambda$load$5(Login.java:589)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at javafx.event.Event.fireEvent(Event.java:198)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at javafx.scene.Node.fireEvent(Node.java:8792)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at javafx.scene.control.Button.fire(Button.java:203)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.maqboolsolutions.esalesanalyst.module.login.Login.lambda$initUI$1(Login.java:230)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at javafx.event.Event.fireEvent(Event.java:198)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at javafx.scene.Scene$KeyHandler.process(Scene.java:4069)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at javafx.scene.Scene.processKeyEvent(Scene.java:2126)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2594)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at java.security.AccessController.doPrivileged(AccessController.java:100)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:248)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:413)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.glass.ui.View.handleKeyEvent(View.java:547)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.glass.ui.View.notifyKey(View.java:971)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Lcom_sun_glass_ui_View_2_0002enotifyKey_00028II_3CI_00029V(JNIJavaCallWrappers.java:0)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at java.lang.Thread.run(Thread.java:829)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:553)
[Sun May 16 16:02:06 PKT 2021][INFO] [SUB]      at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)
```

How can I fix this?

Please, helps me. I am not sure where to put this issue. Let me know if any further info is required.

**Comment by jperedadnr** [comment]
Try running `mvn client:runagent` before building your native image, in order to discover the classes used via reflection in your project.

**Comment by abidmaqbool** [comment]
> Try running `mvn client:runagent` before building your native image, in order to discover the classes used via reflection in your project.

@jperedadnr Thanks for quick reply. I have already tried to running project with  `mvn client:runagent`  my project run successfully with not any error. It have created many file under myproject\src\main\resources\META-INF\native-image

Moreover I am new to reflection, what should I do to solve this problem?

**Comment by jperedadnr** [comment]
Hmm, right, that is the correct way to address the issue... however in this case it won't work:

`treeShowingProperty` was removed from the API in favour of `com.sun.javafx.scene.TreeShowingExpression`:
https://github.com/openjdk/jfx/pull/185/files#diff-4f03a661b7138dc13938d134460abc43b13920679d42b4268c7989f3b7d36e9eL297

And therefore the JavaFX static version built from 17-ea+9 doesn't contain such method, though JFoenix still uses it from an earlier JavaFX version. In fact, there is already filed for this: https://github.com/sshahine/JFoenix/issues/1187

**Comment by abidmaqbool** [comment]
@jperedadnr Okey! Thanks for your important time & support. Will wait until it's fixed by jfoenix devs.

Just curious about, can I used some previous version of javafx, which can solve this problem. Actually I am working on an urgent project. Current version of mine javafx is `15.0.1`

**Comment by jperedadnr** [comment]
The problem is not your JavaFX version, but the one that is ultimately used by the client plugin to create the native image, which, as I said, it is currently based on 17-ea+9. 
So far, the best option would be removing the use of that JFXProgressBar control.
