### ISSUE TITLE
Undefined symbol JVM_GetStackAccessControlContext

### ISSUE THREAD

**Issue by mipastgt** [gluonhq/substrate#973]
I can build my app for Android without problem on a cloud Linux server and install it on my phone locally on a Mac but when I try to run it, it immediately crashes with the following message:

```
07-29 21:49:14.298 16452 16452 D AndroidRuntime: Shutting down VM
07-29 21:49:14.300 16452 16452 E AndroidRuntime: FATAL EXCEPTION: main
07-29 21:49:14.300 16452 16452 E AndroidRuntime: Process: de.mpmediasoft.de.mpmediasoft.mpcopilot.main.mobile, PID: 16452
07-29 21:49:14.300 16452 16452 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "JVM_GetStackAccessControlContext" referenced by "/data/app/de.mpmediasoft.de.mpmediasoft.mpcopilot.main.mobile-inn5hLFgPt65JyYiWxe7sA==/lib/arm64/libsubstrate.so"...
07-29 21:49:14.300 16452 16452 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
07-29 21:49:14.300 16452 16452 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1657)
07-29 21:49:14.300 16452 16452 E AndroidRuntime: 	at com.gluonhq.helloandroid.MainActivity.surfaceCreated(MainActivity.java:104)
07-29 21:49:14.300 16452 16452 E AndroidRuntime: 	at android.view.SurfaceView.updateSurface(SurfaceView.java:753)
07-29 21:49:14.300 16452 16452 E AndroidRuntime: 	at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:154)
07-29 21:49:14.300 16452 16452 E AndroidRuntime: 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1045)
07-29 21:49:14.300 16452 16452 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2808)
07-29 21:49:14.300 16452 16452 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1780)
07-29 21:49:14.300 16452 16452 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7827)
07-29 21:49:14.300 16452 16452 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
07-29 21:49:14.300 16452 16452 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
07-29 21:49:14.300 16452 16452 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:658)
07-29 21:49:14.300 16452 16452 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
07-29 21:49:14.300 16452 16452 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
07-29 21:49:14.300 16452 16452 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
07-29 21:49:14.300 16452 16452 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
07-29 21:49:14.300 16452 16452 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6944)
07-29 21:49:14.300 16452 16452 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-29 21:49:14.300 16452 16452 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
07-29 21:49:14.300 16452 16452 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

```
This was already mentioned at the end of the closed issue https://github.com/gluonhq/substrate/issues/970

### Expected Behavior
It should run and not crash.

### Current Behavior
It crashes.

### Steps to Reproduce
I cannot provide a simple example

### Your Environment
Built on a cloud instance of Ubuntu at Hetzner with gluonfx-maven-plugin 1.0.3 and graalvm-svm-linux-gluon-21.2.0-dev. APK copied to macOS and installed via adb on a Samsung Galaxy S7.

**Comment by johanvos** [comment]
Thanks for the report. We are adding proper fallbacks for those missing symbols, by taking the fallback implementations provided by GraalVM. This is stracked in #1002
